namespace _DoAn.Views
{
    partial class LoginView
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(LoginView));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties33 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties34 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties35 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties36 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.bunifuPictureBox2 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuPictureBox1 = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuShapes1 = new Bunifu.UI.WinForms.BunifuShapes();
            this.tbxUsername = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbxPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnSignin = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuFormControlBox1 = new Bunifu.UI.WinForms.BunifuFormControlBox();
            this.linkLabel1 = new System.Windows.Forms.LinkLabel();
            this.panelLogin = new Bunifu.UI.WinForms.BunifuPanel();
            this.linkShow = new System.Windows.Forms.LinkLabel();
            this.checkShow = new Bunifu.UI.WinForms.BunifuCheckBox();
            this.panelChangePassword = new Bunifu.UI.WinForms.BunifuPanel();
            this.tbxNewPassword = new Bunifu.UI.WinForms.BunifuTextBox();
            this.labelBackToLoginCP = new System.Windows.Forms.LinkLabel();
            this.tbnConfirm = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tbxNewPassword2 = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lbChangePassword = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuShapes3 = new Bunifu.UI.WinForms.BunifuShapes();
            this.panelForgotpassword = new Bunifu.UI.WinForms.BunifuPanel();
            this.lbBackToLoginFP = new System.Windows.Forms.LinkLabel();
            this.lbSend = new System.Windows.Forms.LinkLabel();
            this.btnChangePassword = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.tbxOTP = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbxUsernameFP = new Bunifu.UI.WinForms.BunifuTextBox();
            this.lbForgotpassword = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuShapes2 = new Bunifu.UI.WinForms.BunifuShapes();
            this.lbResend = new System.Windows.Forms.LinkLabel();
            this.bunifuGradientPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).BeginInit();
            this.panelLogin.SuspendLayout();
            this.panelChangePassword.SuspendLayout();
            this.panelForgotpassword.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.bunifuPictureBox2);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuLabel4);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuPictureBox1);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(200)))), ((int)(((byte)(53)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(200)))), ((int)(((byte)(53)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(74)))), ((int)(((byte)(118)))), ((int)(((byte)(18)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(74)))), ((int)(((byte)(118)))), ((int)(((byte)(18)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(497, 619);
            this.bunifuGradientPanel1.TabIndex = 0;
            // 
            // bunifuPictureBox2
            // 
            this.bunifuPictureBox2.AllowFocused = false;
            this.bunifuPictureBox2.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox2.AutoSizeHeight = true;
            this.bunifuPictureBox2.BorderRadius = 0;
            this.bunifuPictureBox2.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox2.Image")));
            this.bunifuPictureBox2.IsCircle = true;
            this.bunifuPictureBox2.Location = new System.Drawing.Point(124, 555);
            this.bunifuPictureBox2.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuPictureBox2.Name = "bunifuPictureBox2";
            this.bunifuPictureBox2.Size = new System.Drawing.Size(32, 32);
            this.bunifuPictureBox2.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox2.TabIndex = 4;
            this.bunifuPictureBox2.TabStop = false;
            this.bunifuPictureBox2.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI", 12F);
            this.bunifuLabel4.Location = new System.Drawing.Point(165, 561);
            this.bunifuLabel4.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(214, 21);
            this.bunifuLabel4.TabIndex = 3;
            this.bunifuLabel4.Text = "Copyright by GREEN Company";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI", 28F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel1.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel1.Location = new System.Drawing.Point(165, 320);
            this.bunifuLabel1.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(182, 50);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "WELCOME";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuPictureBox1
            // 
            this.bunifuPictureBox1.AllowFocused = false;
            this.bunifuPictureBox1.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.bunifuPictureBox1.AutoSizeHeight = true;
            this.bunifuPictureBox1.BorderRadius = 0;
            this.bunifuPictureBox1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuPictureBox1.Image")));
            this.bunifuPictureBox1.IsCircle = true;
            this.bunifuPictureBox1.Location = new System.Drawing.Point(91, 14);
            this.bunifuPictureBox1.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.bunifuPictureBox1.Name = "bunifuPictureBox1";
            this.bunifuPictureBox1.Size = new System.Drawing.Size(332, 332);
            this.bunifuPictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.bunifuPictureBox1.TabIndex = 0;
            this.bunifuPictureBox1.TabStop = false;
            this.bunifuPictureBox1.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Square;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI", 30F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(200)))), ((int)(((byte)(53)))));
            this.bunifuLabel3.Location = new System.Drawing.Point(149, 47);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(123, 54);
            this.bunifuLabel3.TabIndex = 1;
            this.bunifuLabel3.Text = "LOGIN";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuShapes1
            // 
            this.bunifuShapes1.Angle = 0F;
            this.bunifuShapes1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShapes1.BorderColor = System.Drawing.Color.Silver;
            this.bunifuShapes1.BorderThickness = 2;
            this.bunifuShapes1.FillColor = System.Drawing.Color.Transparent;
            this.bunifuShapes1.FillShape = true;
            this.bunifuShapes1.Location = new System.Drawing.Point(149, 67);
            this.bunifuShapes1.Name = "bunifuShapes1";
            this.bunifuShapes1.Shape = Bunifu.UI.WinForms.BunifuShapes.Shapes.Line;
            this.bunifuShapes1.Sides = 5;
            this.bunifuShapes1.Size = new System.Drawing.Size(112, 115);
            this.bunifuShapes1.TabIndex = 2;
            this.bunifuShapes1.Text = "bunifuShapes1";
            // 
            // tbxUsername
            // 
            this.tbxUsername.AcceptsReturn = false;
            this.tbxUsername.AcceptsTab = false;
            this.tbxUsername.AnimationSpeed = 200;
            this.tbxUsername.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxUsername.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxUsername.AutoSizeHeight = true;
            this.tbxUsername.BackColor = System.Drawing.Color.Transparent;
            this.tbxUsername.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxUsername.BackgroundImage")));
            this.tbxUsername.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.tbxUsername.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tbxUsername.BorderColorHover = System.Drawing.Color.Silver;
            this.tbxUsername.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbxUsername.BorderRadius = 10;
            this.tbxUsername.BorderThickness = 1;
            this.tbxUsername.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbxUsername.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxUsername.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxUsername.DefaultFont = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbxUsername.DefaultText = "";
            this.tbxUsername.FillColor = System.Drawing.Color.White;
            this.tbxUsername.HideSelection = true;
            this.tbxUsername.IconLeft = ((System.Drawing.Image)(resources.GetObject("tbxUsername.IconLeft")));
            this.tbxUsername.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxUsername.IconPadding = 10;
            this.tbxUsername.IconRight = null;
            this.tbxUsername.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxUsername.Lines = new string[0];
            this.tbxUsername.Location = new System.Drawing.Point(43, 167);
            this.tbxUsername.MaxLength = 32767;
            this.tbxUsername.MinimumSize = new System.Drawing.Size(2, 2);
            this.tbxUsername.Modified = false;
            this.tbxUsername.Multiline = false;
            this.tbxUsername.Name = "tbxUsername";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxUsername.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.Silver;
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxUsername.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.Silver;
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxUsername.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxUsername.OnIdleState = stateProperties28;
            this.tbxUsername.Padding = new System.Windows.Forms.Padding(3);
            this.tbxUsername.PasswordChar = '\0';
            this.tbxUsername.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxUsername.PlaceholderText = "Enter username";
            this.tbxUsername.ReadOnly = false;
            this.tbxUsername.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxUsername.SelectedText = "";
            this.tbxUsername.SelectionLength = 0;
            this.tbxUsername.SelectionStart = 0;
            this.tbxUsername.ShortcutsEnabled = true;
            this.tbxUsername.Size = new System.Drawing.Size(320, 50);
            this.tbxUsername.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxUsername.TabIndex = 3;
            this.tbxUsername.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxUsername.TextMarginBottom = 0;
            this.tbxUsername.TextMarginLeft = 8;
            this.tbxUsername.TextMarginTop = 1;
            this.tbxUsername.TextPlaceholder = "Enter username";
            this.tbxUsername.UseSystemPasswordChar = false;
            this.tbxUsername.WordWrap = true;
            this.tbxUsername.TextChange += new System.EventHandler(this.tbxUsername_TextChange);
            // 
            // tbxPassword
            // 
            this.tbxPassword.AcceptsReturn = false;
            this.tbxPassword.AcceptsTab = false;
            this.tbxPassword.AnimationSpeed = 200;
            this.tbxPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxPassword.AutoSizeHeight = true;
            this.tbxPassword.BackColor = System.Drawing.Color.Transparent;
            this.tbxPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxPassword.BackgroundImage")));
            this.tbxPassword.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.tbxPassword.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tbxPassword.BorderColorHover = System.Drawing.Color.Silver;
            this.tbxPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbxPassword.BorderRadius = 10;
            this.tbxPassword.BorderThickness = 1;
            this.tbxPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbxPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxPassword.DefaultFont = new System.Drawing.Font("Arial", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbxPassword.DefaultText = "";
            this.tbxPassword.FillColor = System.Drawing.Color.White;
            this.tbxPassword.HideSelection = true;
            this.tbxPassword.IconLeft = ((System.Drawing.Image)(resources.GetObject("tbxPassword.IconLeft")));
            this.tbxPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxPassword.IconPadding = 10;
            this.tbxPassword.IconRight = null;
            this.tbxPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxPassword.Lines = new string[0];
            this.tbxPassword.Location = new System.Drawing.Point(43, 239);
            this.tbxPassword.MaxLength = 32767;
            this.tbxPassword.MinimumSize = new System.Drawing.Size(2, 2);
            this.tbxPassword.Modified = false;
            this.tbxPassword.Multiline = false;
            this.tbxPassword.Name = "tbxPassword";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxPassword.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.Silver;
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxPassword.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.Silver;
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxPassword.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Silver;
            stateProperties32.FillColor = System.Drawing.Color.White;
            stateProperties32.ForeColor = System.Drawing.Color.Empty;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxPassword.OnIdleState = stateProperties32;
            this.tbxPassword.Padding = new System.Windows.Forms.Padding(3);
            this.tbxPassword.PasswordChar = '\0';
            this.tbxPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxPassword.PlaceholderText = "Enter password";
            this.tbxPassword.ReadOnly = false;
            this.tbxPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxPassword.SelectedText = "";
            this.tbxPassword.SelectionLength = 0;
            this.tbxPassword.SelectionStart = 0;
            this.tbxPassword.ShortcutsEnabled = true;
            this.tbxPassword.Size = new System.Drawing.Size(320, 50);
            this.tbxPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxPassword.TabIndex = 4;
            this.tbxPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxPassword.TextMarginBottom = 0;
            this.tbxPassword.TextMarginLeft = 8;
            this.tbxPassword.TextMarginTop = 1;
            this.tbxPassword.TextPlaceholder = "Enter password";
            this.tbxPassword.UseSystemPasswordChar = true;
            this.tbxPassword.WordWrap = true;
            this.tbxPassword.TextChange += new System.EventHandler(this.tbxPassword_TextChange);
            this.tbxPassword.KeyDown += new System.Windows.Forms.KeyEventHandler(this.tbxPassword_KeyDown);
            // 
            // btnSignin
            // 
            this.btnSignin.AllowAnimations = true;
            this.btnSignin.AllowMouseEffects = true;
            this.btnSignin.AllowToggling = false;
            this.btnSignin.AnimationSpeed = 200;
            this.btnSignin.AutoGenerateColors = false;
            this.btnSignin.AutoRoundBorders = false;
            this.btnSignin.AutoSizeLeftIcon = true;
            this.btnSignin.AutoSizeRightIcon = true;
            this.btnSignin.BackColor = System.Drawing.Color.Transparent;
            this.btnSignin.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnSignin.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnSignin.BackgroundImage")));
            this.btnSignin.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignin.ButtonText = "SIGN IN";
            this.btnSignin.ButtonTextMarginLeft = 0;
            this.btnSignin.ColorContrastOnClick = 45;
            this.btnSignin.ColorContrastOnHover = 45;
            this.btnSignin.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnSignin.CustomizableEdges = borderEdges4;
            this.btnSignin.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnSignin.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSignin.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnSignin.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnSignin.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnSignin.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnSignin.ForeColor = System.Drawing.SystemColors.Window;
            this.btnSignin.IconLeft = null;
            this.btnSignin.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnSignin.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSignin.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnSignin.IconMarginLeft = 11;
            this.btnSignin.IconPadding = 10;
            this.btnSignin.IconRight = null;
            this.btnSignin.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnSignin.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnSignin.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnSignin.IconSize = 25;
            this.btnSignin.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnSignin.IdleBorderRadius = 0;
            this.btnSignin.IdleBorderThickness = 0;
            this.btnSignin.IdleFillColor = System.Drawing.Color.Empty;
            this.btnSignin.IdleIconLeftImage = null;
            this.btnSignin.IdleIconRightImage = null;
            this.btnSignin.IndicateFocus = false;
            this.btnSignin.Location = new System.Drawing.Point(46, 360);
            this.btnSignin.Name = "btnSignin";
            this.btnSignin.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnSignin.OnDisabledState.BorderRadius = 15;
            this.btnSignin.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignin.OnDisabledState.BorderThickness = 1;
            this.btnSignin.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnSignin.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnSignin.OnDisabledState.IconLeftImage = null;
            this.btnSignin.OnDisabledState.IconRightImage = null;
            this.btnSignin.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(174)))), ((int)(((byte)(216)))), ((int)(((byte)(115)))));
            this.btnSignin.onHoverState.BorderRadius = 15;
            this.btnSignin.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignin.onHoverState.BorderThickness = 1;
            this.btnSignin.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(174)))), ((int)(((byte)(216)))), ((int)(((byte)(115)))));
            this.btnSignin.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnSignin.onHoverState.IconLeftImage = null;
            this.btnSignin.onHoverState.IconRightImage = null;
            this.btnSignin.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.btnSignin.OnIdleState.BorderRadius = 15;
            this.btnSignin.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignin.OnIdleState.BorderThickness = 1;
            this.btnSignin.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.btnSignin.OnIdleState.ForeColor = System.Drawing.SystemColors.Window;
            this.btnSignin.OnIdleState.IconLeftImage = null;
            this.btnSignin.OnIdleState.IconRightImage = null;
            this.btnSignin.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.btnSignin.OnPressedState.BorderRadius = 15;
            this.btnSignin.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnSignin.OnPressedState.BorderThickness = 1;
            this.btnSignin.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.btnSignin.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnSignin.OnPressedState.IconLeftImage = null;
            this.btnSignin.OnPressedState.IconRightImage = null;
            this.btnSignin.Size = new System.Drawing.Size(317, 60);
            this.btnSignin.TabIndex = 5;
            this.btnSignin.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnSignin.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnSignin.TextMarginLeft = 0;
            this.btnSignin.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnSignin.UseDefaultRadiusAndThickness = true;
            this.btnSignin.Click += new System.EventHandler(this.btnSignin_Click);
            // 
            // bunifuFormControlBox1
            // 
            this.bunifuFormControlBox1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuFormControlBox1.BunifuFormDrag = null;
            this.bunifuFormControlBox1.CloseBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.CloseBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.CloseBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.CloseBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.CloseBoxOptions.HoverColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.CloseBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.CloseBoxOptions.Icon")));
            this.bunifuFormControlBox1.CloseBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.CloseBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.CloseBoxOptions.IconHoverColor = System.Drawing.Color.White;
            this.bunifuFormControlBox1.CloseBoxOptions.IconPressedColor = System.Drawing.Color.White;
            this.bunifuFormControlBox1.CloseBoxOptions.IconSize = new System.Drawing.Size(18, 18);
            this.bunifuFormControlBox1.CloseBoxOptions.PressedColor = System.Drawing.Color.FromArgb(((int)(((byte)(232)))), ((int)(((byte)(17)))), ((int)(((byte)(35)))));
            this.bunifuFormControlBox1.HelpBox = false;
            this.bunifuFormControlBox1.HelpBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.HelpBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.HelpBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.HelpBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.HelpBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.HelpBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.HelpBoxOptions.Icon")));
            this.bunifuFormControlBox1.HelpBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.HelpBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.HelpBoxOptions.IconSize = new System.Drawing.Size(22, 22);
            this.bunifuFormControlBox1.HelpBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Location = new System.Drawing.Point(893, 0);
            this.bunifuFormControlBox1.Margin = new System.Windows.Forms.Padding(3, 4, 3, 4);
            this.bunifuFormControlBox1.MaximizeBox = false;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MaximizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MaximizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MaximizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconAlt = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MaximizeBoxOptions.IconAlt")));
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MaximizeBoxOptions.IconSize = new System.Drawing.Size(16, 16);
            this.bunifuFormControlBox1.MaximizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.MinimizeBox = false;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BackColor = System.Drawing.Color.Transparent;
            this.bunifuFormControlBox1.MinimizeBoxOptions.BorderRadius = 0;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Enabled = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.EnableDefaultAction = true;
            this.bunifuFormControlBox1.MinimizeBoxOptions.HoverColor = System.Drawing.Color.LightGray;
            this.bunifuFormControlBox1.MinimizeBoxOptions.Icon = ((System.Drawing.Image)(resources.GetObject("bunifuFormControlBox1.MinimizeBoxOptions.Icon")));
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconAlt = null;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconHoverColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconPressedColor = System.Drawing.Color.Black;
            this.bunifuFormControlBox1.MinimizeBoxOptions.IconSize = new System.Drawing.Size(14, 14);
            this.bunifuFormControlBox1.MinimizeBoxOptions.PressedColor = System.Drawing.Color.Silver;
            this.bunifuFormControlBox1.Name = "bunifuFormControlBox1";
            this.bunifuFormControlBox1.ShowDesignBorders = false;
            this.bunifuFormControlBox1.Size = new System.Drawing.Size(81, 49);
            this.bunifuFormControlBox1.TabIndex = 6;
            // 
            // linkLabel1
            // 
            this.linkLabel1.AutoSize = true;
            this.linkLabel1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.linkLabel1.Location = new System.Drawing.Point(222, 327);
            this.linkLabel1.Name = "linkLabel1";
            this.linkLabel1.Size = new System.Drawing.Size(153, 20);
            this.linkLabel1.TabIndex = 8;
            this.linkLabel1.TabStop = true;
            this.linkLabel1.Text = "Forgot password?";
            this.linkLabel1.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.linkLabel1_LinkClicked);
            // 
            // panelLogin
            // 
            this.panelLogin.BackgroundColor = System.Drawing.Color.Transparent;
            this.panelLogin.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelLogin.BackgroundImage")));
            this.panelLogin.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panelLogin.BorderColor = System.Drawing.Color.Transparent;
            this.panelLogin.BorderRadius = 3;
            this.panelLogin.BorderThickness = 1;
            this.panelLogin.Controls.Add(this.linkShow);
            this.panelLogin.Controls.Add(this.checkShow);
            this.panelLogin.Controls.Add(this.linkLabel1);
            this.panelLogin.Controls.Add(this.btnSignin);
            this.panelLogin.Controls.Add(this.tbxPassword);
            this.panelLogin.Controls.Add(this.tbxUsername);
            this.panelLogin.Controls.Add(this.bunifuLabel3);
            this.panelLogin.Controls.Add(this.bunifuShapes1);
            this.panelLogin.Location = new System.Drawing.Point(530, 78);
            this.panelLogin.Name = "panelLogin";
            this.panelLogin.ShowBorders = true;
            this.panelLogin.Size = new System.Drawing.Size(414, 460);
            this.panelLogin.TabIndex = 9;
            // 
            // linkShow
            // 
            this.linkShow.AutoSize = true;
            this.linkShow.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))), System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.linkShow.Location = new System.Drawing.Point(205, 296);
            this.linkShow.Name = "linkShow";
            this.linkShow.Size = new System.Drawing.Size(170, 20);
            this.linkShow.TabIndex = 10;
            this.linkShow.TabStop = true;
            this.linkShow.Text = "Show the password ";
            // 
            // checkShow
            // 
            this.checkShow.AllowBindingControlAnimation = true;
            this.checkShow.AllowBindingControlColorChanges = false;
            this.checkShow.AllowBindingControlLocation = true;
            this.checkShow.AllowCheckBoxAnimation = false;
            this.checkShow.AllowCheckmarkAnimation = true;
            this.checkShow.AllowOnHoverStates = true;
            this.checkShow.AutoCheck = true;
            this.checkShow.BackColor = System.Drawing.Color.Transparent;
            this.checkShow.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("checkShow.BackgroundImage")));
            this.checkShow.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Zoom;
            this.checkShow.BindingControlPosition = Bunifu.UI.WinForms.BunifuCheckBox.BindingControlPositions.Right;
            this.checkShow.BorderRadius = 12;
            this.checkShow.Checked = false;
            this.checkShow.CheckState = Bunifu.UI.WinForms.BunifuCheckBox.CheckStates.Unchecked;
            this.checkShow.Cursor = System.Windows.Forms.Cursors.Default;
            this.checkShow.CustomCheckmarkImage = null;
            this.checkShow.Location = new System.Drawing.Point(177, 295);
            this.checkShow.MinimumSize = new System.Drawing.Size(17, 17);
            this.checkShow.Name = "checkShow";
            this.checkShow.OnCheck.BorderColor = System.Drawing.Color.DodgerBlue;
            this.checkShow.OnCheck.BorderRadius = 12;
            this.checkShow.OnCheck.BorderThickness = 2;
            this.checkShow.OnCheck.CheckBoxColor = System.Drawing.Color.DodgerBlue;
            this.checkShow.OnCheck.CheckmarkColor = System.Drawing.Color.White;
            this.checkShow.OnCheck.CheckmarkThickness = 2;
            this.checkShow.OnDisable.BorderColor = System.Drawing.Color.LightGray;
            this.checkShow.OnDisable.BorderRadius = 12;
            this.checkShow.OnDisable.BorderThickness = 2;
            this.checkShow.OnDisable.CheckBoxColor = System.Drawing.Color.Transparent;
            this.checkShow.OnDisable.CheckmarkColor = System.Drawing.Color.LightGray;
            this.checkShow.OnDisable.CheckmarkThickness = 2;
            this.checkShow.OnHoverChecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.checkShow.OnHoverChecked.BorderRadius = 12;
            this.checkShow.OnHoverChecked.BorderThickness = 2;
            this.checkShow.OnHoverChecked.CheckBoxColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.checkShow.OnHoverChecked.CheckmarkColor = System.Drawing.Color.White;
            this.checkShow.OnHoverChecked.CheckmarkThickness = 2;
            this.checkShow.OnHoverUnchecked.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.checkShow.OnHoverUnchecked.BorderRadius = 12;
            this.checkShow.OnHoverUnchecked.BorderThickness = 1;
            this.checkShow.OnHoverUnchecked.CheckBoxColor = System.Drawing.Color.Transparent;
            this.checkShow.OnUncheck.BorderColor = System.Drawing.Color.DarkGray;
            this.checkShow.OnUncheck.BorderRadius = 12;
            this.checkShow.OnUncheck.BorderThickness = 1;
            this.checkShow.OnUncheck.CheckBoxColor = System.Drawing.Color.Transparent;
            this.checkShow.Size = new System.Drawing.Size(21, 21);
            this.checkShow.Style = Bunifu.UI.WinForms.BunifuCheckBox.CheckBoxStyles.Bunifu;
            this.checkShow.TabIndex = 9;
            this.checkShow.ThreeState = false;
            this.checkShow.ToolTipText = null;
            // 
            // panelChangePassword
            // 
            this.panelChangePassword.BackgroundColor = System.Drawing.Color.Transparent;
            this.panelChangePassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelChangePassword.BackgroundImage")));
            this.panelChangePassword.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panelChangePassword.BorderColor = System.Drawing.Color.Transparent;
            this.panelChangePassword.BorderRadius = 3;
            this.panelChangePassword.BorderThickness = 1;
            this.panelChangePassword.Controls.Add(this.tbxNewPassword);
            this.panelChangePassword.Controls.Add(this.labelBackToLoginCP);
            this.panelChangePassword.Controls.Add(this.tbnConfirm);
            this.panelChangePassword.Controls.Add(this.tbxNewPassword2);
            this.panelChangePassword.Controls.Add(this.lbChangePassword);
            this.panelChangePassword.Controls.Add(this.bunifuShapes3);
            this.panelChangePassword.Location = new System.Drawing.Point(530, 78);
            this.panelChangePassword.Name = "panelChangePassword";
            this.panelChangePassword.ShowBorders = true;
            this.panelChangePassword.Size = new System.Drawing.Size(430, 480);
            this.panelChangePassword.TabIndex = 10;
            // 
            // tbxNewPassword
            // 
            this.tbxNewPassword.AcceptsReturn = false;
            this.tbxNewPassword.AcceptsTab = false;
            this.tbxNewPassword.AnimationSpeed = 200;
            this.tbxNewPassword.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxNewPassword.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxNewPassword.AutoSizeHeight = true;
            this.tbxNewPassword.BackColor = System.Drawing.Color.Transparent;
            this.tbxNewPassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxNewPassword.BackgroundImage")));
            this.tbxNewPassword.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.tbxNewPassword.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tbxNewPassword.BorderColorHover = System.Drawing.Color.Silver;
            this.tbxNewPassword.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbxNewPassword.BorderRadius = 10;
            this.tbxNewPassword.BorderThickness = 1;
            this.tbxNewPassword.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbxNewPassword.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxNewPassword.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxNewPassword.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbxNewPassword.DefaultText = "";
            this.tbxNewPassword.FillColor = System.Drawing.Color.White;
            this.tbxNewPassword.HideSelection = true;
            this.tbxNewPassword.IconLeft = ((System.Drawing.Image)(resources.GetObject("tbxNewPassword.IconLeft")));
            this.tbxNewPassword.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxNewPassword.IconPadding = 10;
            this.tbxNewPassword.IconRight = null;
            this.tbxNewPassword.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxNewPassword.Lines = new string[0];
            this.tbxNewPassword.Location = new System.Drawing.Point(55, 163);
            this.tbxNewPassword.MaxLength = 32767;
            this.tbxNewPassword.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbxNewPassword.Modified = false;
            this.tbxNewPassword.Multiline = false;
            this.tbxNewPassword.Name = "tbxNewPassword";
            stateProperties33.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            stateProperties33.FillColor = System.Drawing.Color.Empty;
            stateProperties33.ForeColor = System.Drawing.Color.Empty;
            stateProperties33.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxNewPassword.OnActiveState = stateProperties33;
            stateProperties34.BorderColor = System.Drawing.Color.Silver;
            stateProperties34.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties34.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties34.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxNewPassword.OnDisabledState = stateProperties34;
            stateProperties35.BorderColor = System.Drawing.Color.Silver;
            stateProperties35.FillColor = System.Drawing.Color.Empty;
            stateProperties35.ForeColor = System.Drawing.Color.Empty;
            stateProperties35.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxNewPassword.OnHoverState = stateProperties35;
            stateProperties36.BorderColor = System.Drawing.Color.Silver;
            stateProperties36.FillColor = System.Drawing.Color.White;
            stateProperties36.ForeColor = System.Drawing.Color.Empty;
            stateProperties36.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxNewPassword.OnIdleState = stateProperties36;
            this.tbxNewPassword.Padding = new System.Windows.Forms.Padding(3);
            this.tbxNewPassword.PasswordChar = '\0';
            this.tbxNewPassword.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxNewPassword.PlaceholderText = "Enter password ";
            this.tbxNewPassword.ReadOnly = false;
            this.tbxNewPassword.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxNewPassword.SelectedText = "";
            this.tbxNewPassword.SelectionLength = 0;
            this.tbxNewPassword.SelectionStart = 0;
            this.tbxNewPassword.ShortcutsEnabled = true;
            this.tbxNewPassword.Size = new System.Drawing.Size(320, 60);
            this.tbxNewPassword.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxNewPassword.TabIndex = 9;
            this.tbxNewPassword.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxNewPassword.TextMarginBottom = 0;
            this.tbxNewPassword.TextMarginLeft = 8;
            this.tbxNewPassword.TextMarginTop = 1;
            this.tbxNewPassword.TextPlaceholder = "Enter password ";
            this.tbxNewPassword.UseSystemPasswordChar = true;
            this.tbxNewPassword.WordWrap = true;
            // 
            // labelBackToLoginCP
            // 
            this.labelBackToLoginCP.AutoSize = true;
            this.labelBackToLoginCP.Font = new System.Drawing.Font("Microsoft Sans Serif", 13F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.labelBackToLoginCP.Location = new System.Drawing.Point(62, 348);
            this.labelBackToLoginCP.Name = "labelBackToLoginCP";
            this.labelBackToLoginCP.Size = new System.Drawing.Size(126, 22);
            this.labelBackToLoginCP.TabIndex = 8;
            this.labelBackToLoginCP.TabStop = true;
            this.labelBackToLoginCP.Text = "Back to login";
            this.labelBackToLoginCP.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.lbBackToLogin_LinkClicked);
            // 
            // tbnConfirm
            // 
            this.tbnConfirm.AllowAnimations = true;
            this.tbnConfirm.AllowMouseEffects = true;
            this.tbnConfirm.AllowToggling = false;
            this.tbnConfirm.AnimationSpeed = 200;
            this.tbnConfirm.AutoGenerateColors = false;
            this.tbnConfirm.AutoRoundBorders = false;
            this.tbnConfirm.AutoSizeLeftIcon = true;
            this.tbnConfirm.AutoSizeRightIcon = true;
            this.tbnConfirm.BackColor = System.Drawing.Color.Transparent;
            this.tbnConfirm.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.tbnConfirm.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbnConfirm.BackgroundImage")));
            this.tbnConfirm.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tbnConfirm.ButtonText = "Confirm";
            this.tbnConfirm.ButtonTextMarginLeft = 0;
            this.tbnConfirm.ColorContrastOnClick = 45;
            this.tbnConfirm.ColorContrastOnHover = 45;
            this.tbnConfirm.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.tbnConfirm.CustomizableEdges = borderEdges5;
            this.tbnConfirm.DialogResult = System.Windows.Forms.DialogResult.None;
            this.tbnConfirm.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.tbnConfirm.DisabledFillColor = System.Drawing.Color.Empty;
            this.tbnConfirm.DisabledForecolor = System.Drawing.Color.Empty;
            this.tbnConfirm.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.tbnConfirm.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbnConfirm.ForeColor = System.Drawing.Color.White;
            this.tbnConfirm.IconLeft = null;
            this.tbnConfirm.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.tbnConfirm.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.tbnConfirm.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.tbnConfirm.IconMarginLeft = 11;
            this.tbnConfirm.IconPadding = 10;
            this.tbnConfirm.IconRight = null;
            this.tbnConfirm.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.tbnConfirm.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.tbnConfirm.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.tbnConfirm.IconSize = 25;
            this.tbnConfirm.IdleBorderColor = System.Drawing.Color.Empty;
            this.tbnConfirm.IdleBorderRadius = 0;
            this.tbnConfirm.IdleBorderThickness = 0;
            this.tbnConfirm.IdleFillColor = System.Drawing.Color.Empty;
            this.tbnConfirm.IdleIconLeftImage = null;
            this.tbnConfirm.IdleIconRightImage = null;
            this.tbnConfirm.IndicateFocus = false;
            this.tbnConfirm.Location = new System.Drawing.Point(194, 330);
            this.tbnConfirm.Name = "tbnConfirm";
            this.tbnConfirm.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.tbnConfirm.OnDisabledState.BorderRadius = 15;
            this.tbnConfirm.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tbnConfirm.OnDisabledState.BorderThickness = 1;
            this.tbnConfirm.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbnConfirm.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.tbnConfirm.OnDisabledState.IconLeftImage = null;
            this.tbnConfirm.OnDisabledState.IconRightImage = null;
            this.tbnConfirm.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(174)))), ((int)(((byte)(216)))), ((int)(((byte)(115)))));
            this.tbnConfirm.onHoverState.BorderRadius = 15;
            this.tbnConfirm.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tbnConfirm.onHoverState.BorderThickness = 1;
            this.tbnConfirm.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(174)))), ((int)(((byte)(216)))), ((int)(((byte)(115)))));
            this.tbnConfirm.onHoverState.ForeColor = System.Drawing.Color.White;
            this.tbnConfirm.onHoverState.IconLeftImage = null;
            this.tbnConfirm.onHoverState.IconRightImage = null;
            this.tbnConfirm.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.tbnConfirm.OnIdleState.BorderRadius = 15;
            this.tbnConfirm.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tbnConfirm.OnIdleState.BorderThickness = 1;
            this.tbnConfirm.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.tbnConfirm.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.tbnConfirm.OnIdleState.IconLeftImage = null;
            this.tbnConfirm.OnIdleState.IconRightImage = null;
            this.tbnConfirm.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.tbnConfirm.OnPressedState.BorderRadius = 15;
            this.tbnConfirm.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.tbnConfirm.OnPressedState.BorderThickness = 1;
            this.tbnConfirm.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.tbnConfirm.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.tbnConfirm.OnPressedState.IconLeftImage = null;
            this.tbnConfirm.OnPressedState.IconRightImage = null;
            this.tbnConfirm.Size = new System.Drawing.Size(184, 63);
            this.tbnConfirm.TabIndex = 5;
            this.tbnConfirm.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.tbnConfirm.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.tbnConfirm.TextMarginLeft = 0;
            this.tbnConfirm.TextPadding = new System.Windows.Forms.Padding(0);
            this.tbnConfirm.UseDefaultRadiusAndThickness = true;
            this.tbnConfirm.Click += new System.EventHandler(this.tbnConfirm_Click);
            // 
            // tbxNewPassword2
            // 
            this.tbxNewPassword2.AcceptsReturn = false;
            this.tbxNewPassword2.AcceptsTab = false;
            this.tbxNewPassword2.AnimationSpeed = 200;
            this.tbxNewPassword2.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxNewPassword2.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxNewPassword2.AutoSizeHeight = true;
            this.tbxNewPassword2.BackColor = System.Drawing.Color.Transparent;
            this.tbxNewPassword2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxNewPassword2.BackgroundImage")));
            this.tbxNewPassword2.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.tbxNewPassword2.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tbxNewPassword2.BorderColorHover = System.Drawing.Color.Silver;
            this.tbxNewPassword2.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbxNewPassword2.BorderRadius = 10;
            this.tbxNewPassword2.BorderThickness = 1;
            this.tbxNewPassword2.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbxNewPassword2.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxNewPassword2.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxNewPassword2.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbxNewPassword2.DefaultText = "";
            this.tbxNewPassword2.FillColor = System.Drawing.Color.White;
            this.tbxNewPassword2.HideSelection = true;
            this.tbxNewPassword2.IconLeft = ((System.Drawing.Image)(resources.GetObject("tbxNewPassword2.IconLeft")));
            this.tbxNewPassword2.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxNewPassword2.IconPadding = 10;
            this.tbxNewPassword2.IconRight = null;
            this.tbxNewPassword2.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxNewPassword2.Lines = new string[0];
            this.tbxNewPassword2.Location = new System.Drawing.Point(57, 244);
            this.tbxNewPassword2.MaxLength = 32767;
            this.tbxNewPassword2.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbxNewPassword2.Modified = false;
            this.tbxNewPassword2.Multiline = false;
            this.tbxNewPassword2.Name = "tbxNewPassword2";
            stateProperties37.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxNewPassword2.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.Silver;
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxNewPassword2.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.Silver;
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxNewPassword2.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxNewPassword2.OnIdleState = stateProperties40;
            this.tbxNewPassword2.Padding = new System.Windows.Forms.Padding(3);
            this.tbxNewPassword2.PasswordChar = '\0';
            this.tbxNewPassword2.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxNewPassword2.PlaceholderText = "Enter password again";
            this.tbxNewPassword2.ReadOnly = false;
            this.tbxNewPassword2.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxNewPassword2.SelectedText = "";
            this.tbxNewPassword2.SelectionLength = 0;
            this.tbxNewPassword2.SelectionStart = 0;
            this.tbxNewPassword2.ShortcutsEnabled = true;
            this.tbxNewPassword2.Size = new System.Drawing.Size(320, 60);
            this.tbxNewPassword2.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxNewPassword2.TabIndex = 4;
            this.tbxNewPassword2.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxNewPassword2.TextMarginBottom = 0;
            this.tbxNewPassword2.TextMarginLeft = 8;
            this.tbxNewPassword2.TextMarginTop = 1;
            this.tbxNewPassword2.TextPlaceholder = "Enter password again";
            this.tbxNewPassword2.UseSystemPasswordChar = true;
            this.tbxNewPassword2.WordWrap = true;
            this.tbxNewPassword2.KeyDown += new System.Windows.Forms.KeyEventHandler(this.tbxNewPassword2_KeyDown);
            // 
            // lbChangePassword
            // 
            this.lbChangePassword.AllowParentOverrides = false;
            this.lbChangePassword.AutoEllipsis = false;
            this.lbChangePassword.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbChangePassword.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbChangePassword.Font = new System.Drawing.Font("Segoe UI", 30F, System.Drawing.FontStyle.Bold);
            this.lbChangePassword.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(200)))), ((int)(((byte)(53)))));
            this.lbChangePassword.Location = new System.Drawing.Point(57, 28);
            this.lbChangePassword.Name = "lbChangePassword";
            this.lbChangePassword.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbChangePassword.Size = new System.Drawing.Size(333, 54);
            this.lbChangePassword.TabIndex = 1;
            this.lbChangePassword.Text = "Change Password";
            this.lbChangePassword.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbChangePassword.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuShapes3
            // 
            this.bunifuShapes3.Angle = 0F;
            this.bunifuShapes3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShapes3.BorderColor = System.Drawing.Color.Silver;
            this.bunifuShapes3.BorderThickness = 2;
            this.bunifuShapes3.FillColor = System.Drawing.Color.Transparent;
            this.bunifuShapes3.FillShape = true;
            this.bunifuShapes3.Location = new System.Drawing.Point(177, 88);
            this.bunifuShapes3.Name = "bunifuShapes3";
            this.bunifuShapes3.Shape = Bunifu.UI.WinForms.BunifuShapes.Shapes.Line;
            this.bunifuShapes3.Sides = 5;
            this.bunifuShapes3.Size = new System.Drawing.Size(75, 75);
            this.bunifuShapes3.TabIndex = 2;
            this.bunifuShapes3.Text = "bunifuShapes3";
            // 
            // panelForgotpassword
            // 
            this.panelForgotpassword.BackgroundColor = System.Drawing.Color.Transparent;
            this.panelForgotpassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("panelForgotpassword.BackgroundImage")));
            this.panelForgotpassword.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.panelForgotpassword.BorderColor = System.Drawing.Color.Transparent;
            this.panelForgotpassword.BorderRadius = 3;
            this.panelForgotpassword.BorderThickness = 1;
            this.panelForgotpassword.Controls.Add(this.lbBackToLoginFP);
            this.panelForgotpassword.Controls.Add(this.lbSend);
            this.panelForgotpassword.Controls.Add(this.btnChangePassword);
            this.panelForgotpassword.Controls.Add(this.tbxOTP);
            this.panelForgotpassword.Controls.Add(this.tbxUsernameFP);
            this.panelForgotpassword.Controls.Add(this.lbForgotpassword);
            this.panelForgotpassword.Controls.Add(this.bunifuShapes2);
            this.panelForgotpassword.Controls.Add(this.lbResend);
            this.panelForgotpassword.Location = new System.Drawing.Point(530, 81);
            this.panelForgotpassword.Name = "panelForgotpassword";
            this.panelForgotpassword.ShowBorders = true;
            this.panelForgotpassword.Size = new System.Drawing.Size(430, 460);
            this.panelForgotpassword.TabIndex = 10;
            // 
            // lbBackToLoginFP
            // 
            this.lbBackToLoginFP.AutoSize = true;
            this.lbBackToLoginFP.Font = new System.Drawing.Font("Microsoft Sans Serif", 13F, ((System.Drawing.FontStyle)((System.Drawing.FontStyle.Bold | System.Drawing.FontStyle.Italic))));
            this.lbBackToLoginFP.Location = new System.Drawing.Point(46, 324);
            this.lbBackToLoginFP.Name = "lbBackToLoginFP";
            this.lbBackToLoginFP.Size = new System.Drawing.Size(126, 22);
            this.lbBackToLoginFP.TabIndex = 11;
            this.lbBackToLoginFP.TabStop = true;
            this.lbBackToLoginFP.Text = "Back to login";
            this.lbBackToLoginFP.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.lbBackToLogin_LinkClicked);
            // 
            // lbSend
            // 
            this.lbSend.AutoSize = true;
            this.lbSend.Font = new System.Drawing.Font("Microsoft Sans Serif", 13F);
            this.lbSend.Location = new System.Drawing.Point(50, 248);
            this.lbSend.Name = "lbSend";
            this.lbSend.Size = new System.Drawing.Size(95, 22);
            this.lbSend.TabIndex = 7;
            this.lbSend.TabStop = true;
            this.lbSend.Text = "Send OTP";
            this.lbSend.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.lbSend_LinkClicked);
            // 
            // btnChangePassword
            // 
            this.btnChangePassword.AllowAnimations = true;
            this.btnChangePassword.AllowMouseEffects = true;
            this.btnChangePassword.AllowToggling = false;
            this.btnChangePassword.AnimationSpeed = 200;
            this.btnChangePassword.AutoGenerateColors = false;
            this.btnChangePassword.AutoRoundBorders = false;
            this.btnChangePassword.AutoSizeLeftIcon = true;
            this.btnChangePassword.AutoSizeRightIcon = true;
            this.btnChangePassword.BackColor = System.Drawing.Color.Transparent;
            this.btnChangePassword.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnChangePassword.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnChangePassword.BackgroundImage")));
            this.btnChangePassword.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.ButtonText = "Change Password";
            this.btnChangePassword.ButtonTextMarginLeft = 0;
            this.btnChangePassword.ColorContrastOnClick = 45;
            this.btnChangePassword.ColorContrastOnHover = 45;
            this.btnChangePassword.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnChangePassword.CustomizableEdges = borderEdges6;
            this.btnChangePassword.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnChangePassword.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChangePassword.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnChangePassword.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnChangePassword.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnChangePassword.Font = new System.Drawing.Font("Segoe UI Semibold", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnChangePassword.ForeColor = System.Drawing.Color.White;
            this.btnChangePassword.IconLeft = null;
            this.btnChangePassword.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnChangePassword.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.btnChangePassword.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnChangePassword.IconMarginLeft = 11;
            this.btnChangePassword.IconPadding = 10;
            this.btnChangePassword.IconRight = null;
            this.btnChangePassword.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnChangePassword.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.btnChangePassword.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnChangePassword.IconSize = 25;
            this.btnChangePassword.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnChangePassword.IdleBorderRadius = 0;
            this.btnChangePassword.IdleBorderThickness = 0;
            this.btnChangePassword.IdleFillColor = System.Drawing.Color.Empty;
            this.btnChangePassword.IdleIconLeftImage = null;
            this.btnChangePassword.IdleIconRightImage = null;
            this.btnChangePassword.IndicateFocus = false;
            this.btnChangePassword.Location = new System.Drawing.Point(175, 308);
            this.btnChangePassword.Name = "btnChangePassword";
            this.btnChangePassword.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChangePassword.OnDisabledState.BorderRadius = 15;
            this.btnChangePassword.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.OnDisabledState.BorderThickness = 1;
            this.btnChangePassword.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChangePassword.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChangePassword.OnDisabledState.IconLeftImage = null;
            this.btnChangePassword.OnDisabledState.IconRightImage = null;
            this.btnChangePassword.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(174)))), ((int)(((byte)(216)))), ((int)(((byte)(115)))));
            this.btnChangePassword.onHoverState.BorderRadius = 15;
            this.btnChangePassword.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.onHoverState.BorderThickness = 1;
            this.btnChangePassword.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(174)))), ((int)(((byte)(216)))), ((int)(((byte)(115)))));
            this.btnChangePassword.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnChangePassword.onHoverState.IconLeftImage = null;
            this.btnChangePassword.onHoverState.IconRightImage = null;
            this.btnChangePassword.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.btnChangePassword.OnIdleState.BorderRadius = 15;
            this.btnChangePassword.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.OnIdleState.BorderThickness = 1;
            this.btnChangePassword.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.btnChangePassword.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnChangePassword.OnIdleState.IconLeftImage = null;
            this.btnChangePassword.OnIdleState.IconRightImage = null;
            this.btnChangePassword.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.btnChangePassword.OnPressedState.BorderRadius = 15;
            this.btnChangePassword.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChangePassword.OnPressedState.BorderThickness = 1;
            this.btnChangePassword.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.btnChangePassword.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnChangePassword.OnPressedState.IconLeftImage = null;
            this.btnChangePassword.OnPressedState.IconRightImage = null;
            this.btnChangePassword.Size = new System.Drawing.Size(193, 60);
            this.btnChangePassword.TabIndex = 5;
            this.btnChangePassword.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnChangePassword.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnChangePassword.TextMarginLeft = 0;
            this.btnChangePassword.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnChangePassword.UseDefaultRadiusAndThickness = true;
            this.btnChangePassword.Click += new System.EventHandler(this.tbnChangePassword_Click);
            // 
            // tbxOTP
            // 
            this.tbxOTP.AcceptsReturn = false;
            this.tbxOTP.AcceptsTab = false;
            this.tbxOTP.AnimationSpeed = 200;
            this.tbxOTP.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxOTP.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxOTP.AutoSizeHeight = true;
            this.tbxOTP.BackColor = System.Drawing.Color.Transparent;
            this.tbxOTP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxOTP.BackgroundImage")));
            this.tbxOTP.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.tbxOTP.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tbxOTP.BorderColorHover = System.Drawing.Color.Silver;
            this.tbxOTP.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbxOTP.BorderRadius = 10;
            this.tbxOTP.BorderThickness = 1;
            this.tbxOTP.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbxOTP.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxOTP.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxOTP.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbxOTP.DefaultText = "";
            this.tbxOTP.FillColor = System.Drawing.Color.White;
            this.tbxOTP.HideSelection = true;
            this.tbxOTP.IconLeft = ((System.Drawing.Image)(resources.GetObject("tbxOTP.IconLeft")));
            this.tbxOTP.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxOTP.IconPadding = 10;
            this.tbxOTP.IconRight = null;
            this.tbxOTP.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxOTP.Lines = new string[0];
            this.tbxOTP.Location = new System.Drawing.Point(174, 227);
            this.tbxOTP.MaxLength = 32767;
            this.tbxOTP.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbxOTP.Modified = false;
            this.tbxOTP.Multiline = false;
            this.tbxOTP.Name = "tbxOTP";
            stateProperties41.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxOTP.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.Silver;
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxOTP.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.Silver;
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxOTP.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxOTP.OnIdleState = stateProperties44;
            this.tbxOTP.Padding = new System.Windows.Forms.Padding(3);
            this.tbxOTP.PasswordChar = '\0';
            this.tbxOTP.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxOTP.PlaceholderText = "Enter OTP";
            this.tbxOTP.ReadOnly = false;
            this.tbxOTP.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxOTP.SelectedText = "";
            this.tbxOTP.SelectionLength = 0;
            this.tbxOTP.SelectionStart = 0;
            this.tbxOTP.ShortcutsEnabled = true;
            this.tbxOTP.Size = new System.Drawing.Size(196, 59);
            this.tbxOTP.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxOTP.TabIndex = 4;
            this.tbxOTP.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxOTP.TextMarginBottom = 0;
            this.tbxOTP.TextMarginLeft = 8;
            this.tbxOTP.TextMarginTop = 1;
            this.tbxOTP.TextPlaceholder = "Enter OTP";
            this.tbxOTP.UseSystemPasswordChar = false;
            this.tbxOTP.WordWrap = true;
            this.tbxOTP.KeyDown += new System.Windows.Forms.KeyEventHandler(this.tbxOTP_KeyDown);
            // 
            // tbxUsernameFP
            // 
            this.tbxUsernameFP.AcceptsReturn = false;
            this.tbxUsernameFP.AcceptsTab = false;
            this.tbxUsernameFP.AnimationSpeed = 200;
            this.tbxUsernameFP.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxUsernameFP.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxUsernameFP.AutoSizeHeight = true;
            this.tbxUsernameFP.BackColor = System.Drawing.Color.Transparent;
            this.tbxUsernameFP.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxUsernameFP.BackgroundImage")));
            this.tbxUsernameFP.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            this.tbxUsernameFP.BorderColorDisabled = System.Drawing.Color.Silver;
            this.tbxUsernameFP.BorderColorHover = System.Drawing.Color.Silver;
            this.tbxUsernameFP.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbxUsernameFP.BorderRadius = 10;
            this.tbxUsernameFP.BorderThickness = 1;
            this.tbxUsernameFP.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbxUsernameFP.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxUsernameFP.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxUsernameFP.DefaultFont = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.tbxUsernameFP.DefaultText = "";
            this.tbxUsernameFP.FillColor = System.Drawing.Color.White;
            this.tbxUsernameFP.HideSelection = true;
            this.tbxUsernameFP.IconLeft = ((System.Drawing.Image)(resources.GetObject("tbxUsernameFP.IconLeft")));
            this.tbxUsernameFP.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxUsernameFP.IconPadding = 10;
            this.tbxUsernameFP.IconRight = null;
            this.tbxUsernameFP.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxUsernameFP.Lines = new string[0];
            this.tbxUsernameFP.Location = new System.Drawing.Point(51, 150);
            this.tbxUsernameFP.MaxLength = 32767;
            this.tbxUsernameFP.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbxUsernameFP.Modified = false;
            this.tbxUsernameFP.Multiline = false;
            this.tbxUsernameFP.Name = "tbxUsernameFP";
            stateProperties45.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(138)))), ((int)(((byte)(198)))), ((int)(((byte)(53)))));
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxUsernameFP.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.Silver;
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxUsernameFP.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.Silver;
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxUsernameFP.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxUsernameFP.OnIdleState = stateProperties48;
            this.tbxUsernameFP.Padding = new System.Windows.Forms.Padding(3);
            this.tbxUsernameFP.PasswordChar = '\0';
            this.tbxUsernameFP.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxUsernameFP.PlaceholderText = "Enter username";
            this.tbxUsernameFP.ReadOnly = false;
            this.tbxUsernameFP.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxUsernameFP.SelectedText = "";
            this.tbxUsernameFP.SelectionLength = 0;
            this.tbxUsernameFP.SelectionStart = 0;
            this.tbxUsernameFP.ShortcutsEnabled = true;
            this.tbxUsernameFP.Size = new System.Drawing.Size(320, 55);
            this.tbxUsernameFP.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxUsernameFP.TabIndex = 3;
            this.tbxUsernameFP.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxUsernameFP.TextMarginBottom = 0;
            this.tbxUsernameFP.TextMarginLeft = 8;
            this.tbxUsernameFP.TextMarginTop = 1;
            this.tbxUsernameFP.TextPlaceholder = "Enter username";
            this.tbxUsernameFP.UseSystemPasswordChar = false;
            this.tbxUsernameFP.WordWrap = true;
            // 
            // lbForgotpassword
            // 
            this.lbForgotpassword.AllowParentOverrides = false;
            this.lbForgotpassword.AutoEllipsis = false;
            this.lbForgotpassword.Cursor = System.Windows.Forms.Cursors.Default;
            this.lbForgotpassword.CursorType = System.Windows.Forms.Cursors.Default;
            this.lbForgotpassword.Font = new System.Drawing.Font("Segoe UI", 30F, System.Drawing.FontStyle.Bold);
            this.lbForgotpassword.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(140)))), ((int)(((byte)(200)))), ((int)(((byte)(53)))));
            this.lbForgotpassword.Location = new System.Drawing.Point(51, 32);
            this.lbForgotpassword.Name = "lbForgotpassword";
            this.lbForgotpassword.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lbForgotpassword.Size = new System.Drawing.Size(317, 54);
            this.lbForgotpassword.TabIndex = 1;
            this.lbForgotpassword.Text = "Forgot Password";
            this.lbForgotpassword.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lbForgotpassword.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuShapes2
            // 
            this.bunifuShapes2.Angle = 0F;
            this.bunifuShapes2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShapes2.BorderColor = System.Drawing.Color.Silver;
            this.bunifuShapes2.BorderThickness = 2;
            this.bunifuShapes2.FillColor = System.Drawing.Color.Transparent;
            this.bunifuShapes2.FillShape = true;
            this.bunifuShapes2.Location = new System.Drawing.Point(175, 77);
            this.bunifuShapes2.Name = "bunifuShapes2";
            this.bunifuShapes2.Shape = Bunifu.UI.WinForms.BunifuShapes.Shapes.Line;
            this.bunifuShapes2.Sides = 5;
            this.bunifuShapes2.Size = new System.Drawing.Size(75, 75);
            this.bunifuShapes2.TabIndex = 2;
            this.bunifuShapes2.Text = "bunifuShapes2";
            // 
            // lbResend
            // 
            this.lbResend.AutoSize = true;
            this.lbResend.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F);
            this.lbResend.Location = new System.Drawing.Point(51, 248);
            this.lbResend.Name = "lbResend";
            this.lbResend.Size = new System.Drawing.Size(100, 20);
            this.lbResend.TabIndex = 8;
            this.lbResend.TabStop = true;
            this.lbResend.Text = "Resend OTP";
            this.lbResend.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.lbSend_LinkClicked);
            // 
            // LoginView
            // 
            this.ClientSize = new System.Drawing.Size(972, 619);
            this.Controls.Add(this.bunifuFormControlBox1);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Controls.Add(this.panelLogin);
            this.Controls.Add(this.panelForgotpassword);
            this.Controls.Add(this.panelChangePassword);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Margin = new System.Windows.Forms.Padding(4, 5, 4, 5);
            this.Name = "LoginView";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Login";
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuGradientPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox2)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.bunifuPictureBox1)).EndInit();
            this.panelLogin.ResumeLayout(false);
            this.panelLogin.PerformLayout();
            this.panelChangePassword.ResumeLayout(false);
            this.panelChangePassword.PerformLayout();
            this.panelForgotpassword.ResumeLayout(false);
            this.panelForgotpassword.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuShapes bunifuShapes1;
        private Bunifu.UI.WinForms.BunifuTextBox tbxUsername;
        private Bunifu.UI.WinForms.BunifuTextBox tbxPassword;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnSignin;
        private Bunifu.UI.WinForms.BunifuFormControlBox bunifuFormControlBox1;
        private Bunifu.UI.WinForms.BunifuPictureBox bunifuPictureBox2;
        private System.Windows.Forms.LinkLabel linkLabel1;
        private Bunifu.UI.WinForms.BunifuPanel panelLogin;
        private Bunifu.UI.WinForms.BunifuPanel panelForgotpassword;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnChangePassword;
        private Bunifu.UI.WinForms.BunifuTextBox tbxOTP;
        private Bunifu.UI.WinForms.BunifuTextBox tbxUsernameFP;
        private Bunifu.UI.WinForms.BunifuLabel lbForgotpassword;
        private Bunifu.UI.WinForms.BunifuShapes bunifuShapes2;
        private System.Windows.Forms.LinkLabel lbResend;
        private System.Windows.Forms.LinkLabel lbSend;
        private Bunifu.UI.WinForms.BunifuPanel panelChangePassword;
        private System.Windows.Forms.LinkLabel labelBackToLoginCP;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton tbnConfirm;
        private Bunifu.UI.WinForms.BunifuTextBox tbxNewPassword2;
        private Bunifu.UI.WinForms.BunifuLabel lbChangePassword;
        private Bunifu.UI.WinForms.BunifuShapes bunifuShapes3;
        private System.Windows.Forms.LinkLabel lbBackToLoginFP;
        private Bunifu.UI.WinForms.BunifuTextBox tbxNewPassword;
        private System.Windows.Forms.LinkLabel linkShow;
        private Bunifu.UI.WinForms.BunifuCheckBox checkShow;
    }
}