namespace _DoAn.Views.Supplier
{
    partial class SupplierView
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SupplierView));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.tbxSuplierId = new Bunifu.UI.WinForms.BunifuTextBox();
            this.gbSupplier = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.dtgvSupplier = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.tbxSupplierName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbxEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbxAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbxPhoneNumber = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnEdit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAdd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.label5 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuGroupBox2 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.gbSupplier.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dtgvSupplier)).BeginInit();
            this.bunifuGroupBox1.SuspendLayout();
            this.bunifuGroupBox2.SuspendLayout();
            this.SuspendLayout();
            // 
            // tbxSuplierId
            // 
            this.tbxSuplierId.AcceptsReturn = false;
            this.tbxSuplierId.AcceptsTab = false;
            this.tbxSuplierId.AnimationSpeed = 200;
            this.tbxSuplierId.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxSuplierId.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxSuplierId.AutoSizeHeight = true;
            this.tbxSuplierId.BackColor = System.Drawing.Color.Transparent;
            this.tbxSuplierId.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxSuplierId.BackgroundImage")));
            this.tbxSuplierId.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(133)))), ((int)(((byte)(189)))), ((int)(((byte)(50)))));
            this.tbxSuplierId.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbxSuplierId.BorderColorHover = System.Drawing.Color.DarkGray;
            this.tbxSuplierId.BorderColorIdle = System.Drawing.Color.DarkGray;
            this.tbxSuplierId.BorderRadius = 10;
            this.tbxSuplierId.BorderThickness = 1;
            this.tbxSuplierId.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbxSuplierId.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxSuplierId.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxSuplierId.DefaultFont = new System.Drawing.Font("Segoe UI", 14F);
            this.tbxSuplierId.DefaultText = "";
            this.tbxSuplierId.Enabled = false;
            this.tbxSuplierId.FillColor = System.Drawing.Color.White;
            this.tbxSuplierId.HideSelection = true;
            this.tbxSuplierId.IconLeft = null;
            this.tbxSuplierId.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxSuplierId.IconPadding = 10;
            this.tbxSuplierId.IconRight = null;
            this.tbxSuplierId.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxSuplierId.Lines = new string[0];
            this.tbxSuplierId.Location = new System.Drawing.Point(42, 45);
            this.tbxSuplierId.MaxLength = 32767;
            this.tbxSuplierId.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbxSuplierId.Modified = false;
            this.tbxSuplierId.Multiline = false;
            this.tbxSuplierId.Name = "tbxSuplierId";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(133)))), ((int)(((byte)(189)))), ((int)(((byte)(50)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxSuplierId.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxSuplierId.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxSuplierId.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxSuplierId.OnIdleState = stateProperties4;
            this.tbxSuplierId.Padding = new System.Windows.Forms.Padding(3);
            this.tbxSuplierId.PasswordChar = '\0';
            this.tbxSuplierId.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxSuplierId.PlaceholderText = "ID";
            this.tbxSuplierId.ReadOnly = true;
            this.tbxSuplierId.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxSuplierId.SelectedText = "";
            this.tbxSuplierId.SelectionLength = 0;
            this.tbxSuplierId.SelectionStart = 0;
            this.tbxSuplierId.ShortcutsEnabled = true;
            this.tbxSuplierId.Size = new System.Drawing.Size(353, 47);
            this.tbxSuplierId.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxSuplierId.TabIndex = 27;
            this.tbxSuplierId.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxSuplierId.TextMarginBottom = 0;
            this.tbxSuplierId.TextMarginLeft = 3;
            this.tbxSuplierId.TextMarginTop = 1;
            this.tbxSuplierId.TextPlaceholder = "ID";
            this.tbxSuplierId.UseSystemPasswordChar = false;
            this.tbxSuplierId.WordWrap = true;
            // 
            // gbSupplier
            // 
            this.gbSupplier.BorderColor = System.Drawing.Color.Black;
            this.gbSupplier.BorderRadius = 4;
            this.gbSupplier.BorderThickness = 2;
            this.gbSupplier.Controls.Add(this.dtgvSupplier);
            this.gbSupplier.Font = new System.Drawing.Font("Segoe UI", 10.8F);
            this.gbSupplier.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.gbSupplier.LabelIndent = 10;
            this.gbSupplier.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.gbSupplier.Location = new System.Drawing.Point(58, 300);
            this.gbSupplier.Name = "gbSupplier";
            this.gbSupplier.Size = new System.Drawing.Size(1354, 584);
            this.gbSupplier.TabIndex = 45;
            this.gbSupplier.TabStop = false;
            this.gbSupplier.Text = "Suppliers Table";
            // 
            // dtgvSupplier
            // 
            this.dtgvSupplier.AllowCustomTheming = true;
            this.dtgvSupplier.AllowUserToAddRows = false;
            this.dtgvSupplier.AllowUserToDeleteRows = false;
            this.dtgvSupplier.AllowUserToResizeColumns = false;
            this.dtgvSupplier.AllowUserToResizeRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.Font = new System.Drawing.Font("Microsoft Sans Serif", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle1.SelectionBackColor = System.Drawing.Color.CornflowerBlue;
            dataGridViewCellStyle1.SelectionForeColor = System.Drawing.Color.White;
            this.dtgvSupplier.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dtgvSupplier.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dtgvSupplier.BackgroundColor = System.Drawing.SystemColors.ButtonFace;
            this.dtgvSupplier.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dtgvSupplier.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dtgvSupplier.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.ForestGreen;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtgvSupplier.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dtgvSupplier.ColumnHeadersHeight = 40;
            this.dtgvSupplier.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dtgvSupplier.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtgvSupplier.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtgvSupplier.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtgvSupplier.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dtgvSupplier.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dtgvSupplier.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtgvSupplier.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.ForestGreen;
            this.dtgvSupplier.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dtgvSupplier.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dtgvSupplier.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dtgvSupplier.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dtgvSupplier.CurrentTheme.Name = null;
            this.dtgvSupplier.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dtgvSupplier.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtgvSupplier.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtgvSupplier.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtgvSupplier.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dtgvSupplier.DefaultCellStyle = dataGridViewCellStyle3;
            this.dtgvSupplier.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dtgvSupplier.EnableHeadersVisualStyles = false;
            this.dtgvSupplier.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtgvSupplier.HeaderBackColor = System.Drawing.Color.ForestGreen;
            this.dtgvSupplier.HeaderBgColor = System.Drawing.Color.Empty;
            this.dtgvSupplier.HeaderForeColor = System.Drawing.Color.White;
            this.dtgvSupplier.Location = new System.Drawing.Point(3, 23);
            this.dtgvSupplier.Name = "dtgvSupplier";
            this.dtgvSupplier.ReadOnly = true;
            this.dtgvSupplier.RowHeadersVisible = false;
            this.dtgvSupplier.RowTemplate.Height = 40;
            this.dtgvSupplier.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dtgvSupplier.Size = new System.Drawing.Size(1348, 558);
            this.dtgvSupplier.TabIndex = 61;
            this.dtgvSupplier.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dtgvSupplier.DoubleClick += new System.EventHandler(this.dtgvsuplier_DoubleClick);
            // 
            // tbxSupplierName
            // 
            this.tbxSupplierName.AcceptsReturn = false;
            this.tbxSupplierName.AcceptsTab = false;
            this.tbxSupplierName.AnimationSpeed = 200;
            this.tbxSupplierName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxSupplierName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxSupplierName.AutoSizeHeight = true;
            this.tbxSupplierName.BackColor = System.Drawing.Color.White;
            this.tbxSupplierName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxSupplierName.BackgroundImage")));
            this.tbxSupplierName.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(133)))), ((int)(((byte)(189)))), ((int)(((byte)(50)))));
            this.tbxSupplierName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbxSupplierName.BorderColorHover = System.Drawing.Color.DarkGray;
            this.tbxSupplierName.BorderColorIdle = System.Drawing.Color.DarkGray;
            this.tbxSupplierName.BorderRadius = 10;
            this.tbxSupplierName.BorderThickness = 1;
            this.tbxSupplierName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbxSupplierName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxSupplierName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxSupplierName.DefaultFont = new System.Drawing.Font("Segoe UI", 14F);
            this.tbxSupplierName.DefaultText = "";
            this.tbxSupplierName.FillColor = System.Drawing.Color.White;
            this.tbxSupplierName.HideSelection = true;
            this.tbxSupplierName.IconLeft = null;
            this.tbxSupplierName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxSupplierName.IconPadding = 10;
            this.tbxSupplierName.IconRight = null;
            this.tbxSupplierName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxSupplierName.Lines = new string[0];
            this.tbxSupplierName.Location = new System.Drawing.Point(42, 124);
            this.tbxSupplierName.MaxLength = 32767;
            this.tbxSupplierName.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbxSupplierName.Modified = false;
            this.tbxSupplierName.Multiline = false;
            this.tbxSupplierName.Name = "tbxSupplierName";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(133)))), ((int)(((byte)(189)))), ((int)(((byte)(50)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxSupplierName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxSupplierName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxSupplierName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxSupplierName.OnIdleState = stateProperties8;
            this.tbxSupplierName.Padding = new System.Windows.Forms.Padding(3);
            this.tbxSupplierName.PasswordChar = '\0';
            this.tbxSupplierName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxSupplierName.PlaceholderText = "Supplier Name";
            this.tbxSupplierName.ReadOnly = false;
            this.tbxSupplierName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxSupplierName.SelectedText = "";
            this.tbxSupplierName.SelectionLength = 0;
            this.tbxSupplierName.SelectionStart = 0;
            this.tbxSupplierName.ShortcutsEnabled = true;
            this.tbxSupplierName.Size = new System.Drawing.Size(353, 47);
            this.tbxSupplierName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxSupplierName.TabIndex = 48;
            this.tbxSupplierName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxSupplierName.TextMarginBottom = 0;
            this.tbxSupplierName.TextMarginLeft = 3;
            this.tbxSupplierName.TextMarginTop = 1;
            this.tbxSupplierName.TextPlaceholder = "Supplier Name";
            this.tbxSupplierName.UseSystemPasswordChar = false;
            this.tbxSupplierName.WordWrap = true;
            this.tbxSupplierName.TextChanged += new System.EventHandler(this.tbxSupplierName_TextChanged);
            // 
            // tbxEmail
            // 
            this.tbxEmail.AcceptsReturn = false;
            this.tbxEmail.AcceptsTab = false;
            this.tbxEmail.AnimationSpeed = 200;
            this.tbxEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxEmail.AutoSizeHeight = true;
            this.tbxEmail.BackColor = System.Drawing.Color.Transparent;
            this.tbxEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxEmail.BackgroundImage")));
            this.tbxEmail.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(133)))), ((int)(((byte)(189)))), ((int)(((byte)(50)))));
            this.tbxEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbxEmail.BorderColorHover = System.Drawing.Color.DarkGray;
            this.tbxEmail.BorderColorIdle = System.Drawing.Color.DarkGray;
            this.tbxEmail.BorderRadius = 10;
            this.tbxEmail.BorderThickness = 1;
            this.tbxEmail.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbxEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 14F);
            this.tbxEmail.DefaultText = "";
            this.tbxEmail.FillColor = System.Drawing.Color.White;
            this.tbxEmail.HideSelection = true;
            this.tbxEmail.IconLeft = null;
            this.tbxEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxEmail.IconPadding = 10;
            this.tbxEmail.IconRight = null;
            this.tbxEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxEmail.Lines = new string[0];
            this.tbxEmail.Location = new System.Drawing.Point(42, 200);
            this.tbxEmail.MaxLength = 32767;
            this.tbxEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbxEmail.Modified = false;
            this.tbxEmail.Multiline = false;
            this.tbxEmail.Name = "tbxEmail";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(133)))), ((int)(((byte)(189)))), ((int)(((byte)(50)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxEmail.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxEmail.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxEmail.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxEmail.OnIdleState = stateProperties12;
            this.tbxEmail.Padding = new System.Windows.Forms.Padding(3);
            this.tbxEmail.PasswordChar = '\0';
            this.tbxEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxEmail.PlaceholderText = "Email";
            this.tbxEmail.ReadOnly = false;
            this.tbxEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxEmail.SelectedText = "";
            this.tbxEmail.SelectionLength = 0;
            this.tbxEmail.SelectionStart = 0;
            this.tbxEmail.ShortcutsEnabled = true;
            this.tbxEmail.Size = new System.Drawing.Size(353, 47);
            this.tbxEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxEmail.TabIndex = 49;
            this.tbxEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxEmail.TextMarginBottom = 0;
            this.tbxEmail.TextMarginLeft = 3;
            this.tbxEmail.TextMarginTop = 1;
            this.tbxEmail.TextPlaceholder = "Email";
            this.tbxEmail.UseSystemPasswordChar = false;
            this.tbxEmail.WordWrap = true;
            this.tbxEmail.TextChanged += new System.EventHandler(this.tbxSupplierName_TextChanged);
            // 
            // tbxAddress
            // 
            this.tbxAddress.AcceptsReturn = false;
            this.tbxAddress.AcceptsTab = false;
            this.tbxAddress.AnimationSpeed = 200;
            this.tbxAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxAddress.AutoSizeHeight = true;
            this.tbxAddress.BackColor = System.Drawing.Color.Transparent;
            this.tbxAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxAddress.BackgroundImage")));
            this.tbxAddress.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(133)))), ((int)(((byte)(189)))), ((int)(((byte)(50)))));
            this.tbxAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbxAddress.BorderColorHover = System.Drawing.Color.DarkGray;
            this.tbxAddress.BorderColorIdle = System.Drawing.Color.DarkGray;
            this.tbxAddress.BorderRadius = 10;
            this.tbxAddress.BorderThickness = 1;
            this.tbxAddress.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbxAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 14F);
            this.tbxAddress.DefaultText = "";
            this.tbxAddress.FillColor = System.Drawing.Color.White;
            this.tbxAddress.HideSelection = true;
            this.tbxAddress.IconLeft = null;
            this.tbxAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxAddress.IconPadding = 10;
            this.tbxAddress.IconRight = null;
            this.tbxAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxAddress.Lines = new string[0];
            this.tbxAddress.Location = new System.Drawing.Point(536, 45);
            this.tbxAddress.MaxLength = 32767;
            this.tbxAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbxAddress.Modified = false;
            this.tbxAddress.Multiline = true;
            this.tbxAddress.Name = "tbxAddress";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(133)))), ((int)(((byte)(189)))), ((int)(((byte)(50)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxAddress.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxAddress.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxAddress.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxAddress.OnIdleState = stateProperties16;
            this.tbxAddress.Padding = new System.Windows.Forms.Padding(3);
            this.tbxAddress.PasswordChar = '\0';
            this.tbxAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxAddress.PlaceholderText = "Address";
            this.tbxAddress.ReadOnly = false;
            this.tbxAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxAddress.SelectedText = "";
            this.tbxAddress.SelectionLength = 0;
            this.tbxAddress.SelectionStart = 0;
            this.tbxAddress.ShortcutsEnabled = true;
            this.tbxAddress.Size = new System.Drawing.Size(402, 126);
            this.tbxAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxAddress.TabIndex = 50;
            this.tbxAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxAddress.TextMarginBottom = 0;
            this.tbxAddress.TextMarginLeft = 3;
            this.tbxAddress.TextMarginTop = 1;
            this.tbxAddress.TextPlaceholder = "Address";
            this.tbxAddress.UseSystemPasswordChar = false;
            this.tbxAddress.WordWrap = true;
            this.tbxAddress.TextChanged += new System.EventHandler(this.tbxSupplierName_TextChanged);
            // 
            // tbxPhoneNumber
            // 
            this.tbxPhoneNumber.AcceptsReturn = false;
            this.tbxPhoneNumber.AcceptsTab = false;
            this.tbxPhoneNumber.AnimationSpeed = 200;
            this.tbxPhoneNumber.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxPhoneNumber.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxPhoneNumber.AutoSizeHeight = true;
            this.tbxPhoneNumber.BackColor = System.Drawing.Color.Transparent;
            this.tbxPhoneNumber.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxPhoneNumber.BackgroundImage")));
            this.tbxPhoneNumber.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(133)))), ((int)(((byte)(189)))), ((int)(((byte)(50)))));
            this.tbxPhoneNumber.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbxPhoneNumber.BorderColorHover = System.Drawing.Color.DarkGray;
            this.tbxPhoneNumber.BorderColorIdle = System.Drawing.Color.DarkGray;
            this.tbxPhoneNumber.BorderRadius = 10;
            this.tbxPhoneNumber.BorderThickness = 1;
            this.tbxPhoneNumber.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbxPhoneNumber.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxPhoneNumber.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxPhoneNumber.DefaultFont = new System.Drawing.Font("Segoe UI", 14F);
            this.tbxPhoneNumber.DefaultText = "";
            this.tbxPhoneNumber.FillColor = System.Drawing.Color.White;
            this.tbxPhoneNumber.HideSelection = true;
            this.tbxPhoneNumber.IconLeft = null;
            this.tbxPhoneNumber.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxPhoneNumber.IconPadding = 10;
            this.tbxPhoneNumber.IconRight = null;
            this.tbxPhoneNumber.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxPhoneNumber.Lines = new string[0];
            this.tbxPhoneNumber.Location = new System.Drawing.Point(536, 200);
            this.tbxPhoneNumber.MaxLength = 32767;
            this.tbxPhoneNumber.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbxPhoneNumber.Modified = false;
            this.tbxPhoneNumber.Multiline = false;
            this.tbxPhoneNumber.Name = "tbxPhoneNumber";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(133)))), ((int)(((byte)(189)))), ((int)(((byte)(50)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxPhoneNumber.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxPhoneNumber.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxPhoneNumber.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.DarkGray;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxPhoneNumber.OnIdleState = stateProperties20;
            this.tbxPhoneNumber.Padding = new System.Windows.Forms.Padding(3);
            this.tbxPhoneNumber.PasswordChar = '\0';
            this.tbxPhoneNumber.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxPhoneNumber.PlaceholderText = "Phone Number";
            this.tbxPhoneNumber.ReadOnly = false;
            this.tbxPhoneNumber.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxPhoneNumber.SelectedText = "";
            this.tbxPhoneNumber.SelectionLength = 0;
            this.tbxPhoneNumber.SelectionStart = 0;
            this.tbxPhoneNumber.ShortcutsEnabled = true;
            this.tbxPhoneNumber.Size = new System.Drawing.Size(402, 47);
            this.tbxPhoneNumber.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxPhoneNumber.TabIndex = 51;
            this.tbxPhoneNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxPhoneNumber.TextMarginBottom = 0;
            this.tbxPhoneNumber.TextMarginLeft = 3;
            this.tbxPhoneNumber.TextMarginTop = 1;
            this.tbxPhoneNumber.TextPlaceholder = "Phone Number";
            this.tbxPhoneNumber.UseSystemPasswordChar = false;
            this.tbxPhoneNumber.WordWrap = true;
            this.tbxPhoneNumber.TextChanged += new System.EventHandler(this.tbxSupplierName_TextChanged);
            // 
            // btnDelete
            // 
            this.btnDelete.AllowAnimations = true;
            this.btnDelete.AllowMouseEffects = true;
            this.btnDelete.AllowToggling = false;
            this.btnDelete.AnimationSpeed = 200;
            this.btnDelete.AutoGenerateColors = false;
            this.btnDelete.AutoRoundBorders = false;
            this.btnDelete.AutoSizeLeftIcon = true;
            this.btnDelete.AutoSizeRightIcon = true;
            this.btnDelete.BackColor = System.Drawing.Color.Transparent;
            this.btnDelete.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnDelete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDelete.BackgroundImage")));
            this.btnDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.ButtonText = "Delete";
            this.btnDelete.ButtonTextMarginLeft = 0;
            this.btnDelete.ColorContrastOnClick = 45;
            this.btnDelete.ColorContrastOnHover = 45;
            this.btnDelete.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnDelete.CustomizableEdges = borderEdges1;
            this.btnDelete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDelete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelete.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnDelete.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDelete.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.btnDelete.ForeColor = System.Drawing.Color.Red;
            this.btnDelete.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnDelete.IconLeft")));
            this.btnDelete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDelete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelete.IconLeftPadding = new System.Windows.Forms.Padding(18, 3, 3, 3);
            this.btnDelete.IconMarginLeft = 11;
            this.btnDelete.IconPadding = 16;
            this.btnDelete.IconRight = null;
            this.btnDelete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDelete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDelete.IconSize = 25;
            this.btnDelete.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnDelete.IdleBorderRadius = 0;
            this.btnDelete.IdleBorderThickness = 0;
            this.btnDelete.IdleFillColor = System.Drawing.Color.Empty;
            this.btnDelete.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnDelete.IdleIconLeftImage")));
            this.btnDelete.IdleIconRightImage = null;
            this.btnDelete.IndicateFocus = false;
            this.btnDelete.Location = new System.Drawing.Point(52, 187);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelete.OnDisabledState.BorderRadius = 15;
            this.btnDelete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnDisabledState.BorderThickness = 1;
            this.btnDelete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelete.OnDisabledState.IconLeftImage = null;
            this.btnDelete.OnDisabledState.IconRightImage = null;
            this.btnDelete.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(76)))), ((int)(((byte)(76)))));
            this.btnDelete.onHoverState.BorderRadius = 15;
            this.btnDelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.onHoverState.BorderThickness = 1;
            this.btnDelete.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(249)))), ((int)(((byte)(76)))), ((int)(((byte)(76)))));
            this.btnDelete.onHoverState.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.btnDelete.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnDelete.onHoverState.IconLeftImage")));
            this.btnDelete.onHoverState.IconRightImage = null;
            this.btnDelete.OnIdleState.BorderColor = System.Drawing.Color.Red;
            this.btnDelete.OnIdleState.BorderRadius = 15;
            this.btnDelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnIdleState.BorderThickness = 1;
            this.btnDelete.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.btnDelete.OnIdleState.ForeColor = System.Drawing.Color.Red;
            this.btnDelete.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnDelete.OnIdleState.IconLeftImage")));
            this.btnDelete.OnIdleState.IconRightImage = null;
            this.btnDelete.OnPressedState.BorderColor = System.Drawing.SystemColors.ControlDark;
            this.btnDelete.OnPressedState.BorderRadius = 15;
            this.btnDelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnPressedState.BorderThickness = 1;
            this.btnDelete.OnPressedState.FillColor = System.Drawing.SystemColors.Control;
            this.btnDelete.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnDelete.OnPressedState.IconLeftImage = null;
            this.btnDelete.OnPressedState.IconRightImage = null;
            this.btnDelete.Size = new System.Drawing.Size(125, 65);
            this.btnDelete.TabIndex = 54;
            this.btnDelete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDelete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDelete.TextMarginLeft = 0;
            this.btnDelete.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btnDelete.UseDefaultRadiusAndThickness = true;
            this.btnDelete.Click += new System.EventHandler(this.btnDelete_Click_1);
            // 
            // btnEdit
            // 
            this.btnEdit.AllowAnimations = true;
            this.btnEdit.AllowMouseEffects = true;
            this.btnEdit.AllowToggling = false;
            this.btnEdit.AnimationSpeed = 200;
            this.btnEdit.AutoGenerateColors = false;
            this.btnEdit.AutoRoundBorders = false;
            this.btnEdit.AutoSizeLeftIcon = true;
            this.btnEdit.AutoSizeRightIcon = true;
            this.btnEdit.BackColor = System.Drawing.Color.Transparent;
            this.btnEdit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnEdit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEdit.BackgroundImage")));
            this.btnEdit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEdit.ButtonText = "Edit";
            this.btnEdit.ButtonTextMarginLeft = 0;
            this.btnEdit.ColorContrastOnClick = 45;
            this.btnEdit.ColorContrastOnHover = 45;
            this.btnEdit.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnEdit.CustomizableEdges = borderEdges2;
            this.btnEdit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEdit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEdit.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnEdit.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnEdit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEdit.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.btnEdit.ForeColor = System.Drawing.Color.Orange;
            this.btnEdit.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnEdit.IconLeft")));
            this.btnEdit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEdit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEdit.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btnEdit.IconMarginLeft = 11;
            this.btnEdit.IconPadding = 16;
            this.btnEdit.IconRight = null;
            this.btnEdit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEdit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEdit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEdit.IconSize = 25;
            this.btnEdit.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnEdit.IdleBorderRadius = 0;
            this.btnEdit.IdleBorderThickness = 0;
            this.btnEdit.IdleFillColor = System.Drawing.Color.Empty;
            this.btnEdit.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnEdit.IdleIconLeftImage")));
            this.btnEdit.IdleIconRightImage = null;
            this.btnEdit.IndicateFocus = false;
            this.btnEdit.Location = new System.Drawing.Point(52, 106);
            this.btnEdit.Name = "btnEdit";
            this.btnEdit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEdit.OnDisabledState.BorderRadius = 15;
            this.btnEdit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEdit.OnDisabledState.BorderThickness = 1;
            this.btnEdit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEdit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEdit.OnDisabledState.IconLeftImage = null;
            this.btnEdit.OnDisabledState.IconRightImage = null;
            this.btnEdit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(183)))), ((int)(((byte)(59)))));
            this.btnEdit.onHoverState.BorderRadius = 15;
            this.btnEdit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEdit.onHoverState.BorderThickness = 1;
            this.btnEdit.onHoverState.FillColor = System.Drawing.SystemColors.Control;
            this.btnEdit.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(252)))), ((int)(((byte)(183)))), ((int)(((byte)(59)))));
            this.btnEdit.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnEdit.onHoverState.IconLeftImage")));
            this.btnEdit.onHoverState.IconRightImage = null;
            this.btnEdit.OnIdleState.BorderColor = System.Drawing.SystemColors.ControlDarkDark;
            this.btnEdit.OnIdleState.BorderRadius = 15;
            this.btnEdit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEdit.OnIdleState.BorderThickness = 1;
            this.btnEdit.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.btnEdit.OnIdleState.ForeColor = System.Drawing.Color.Orange;
            this.btnEdit.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnEdit.OnIdleState.IconLeftImage")));
            this.btnEdit.OnIdleState.IconRightImage = null;
            this.btnEdit.OnPressedState.BorderColor = System.Drawing.SystemColors.ControlDark;
            this.btnEdit.OnPressedState.BorderRadius = 15;
            this.btnEdit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEdit.OnPressedState.BorderThickness = 1;
            this.btnEdit.OnPressedState.FillColor = System.Drawing.SystemColors.Control;
            this.btnEdit.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnEdit.OnPressedState.IconLeftImage = null;
            this.btnEdit.OnPressedState.IconRightImage = null;
            this.btnEdit.Size = new System.Drawing.Size(125, 65);
            this.btnEdit.TabIndex = 53;
            this.btnEdit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEdit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEdit.TextMarginLeft = 0;
            this.btnEdit.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btnEdit.UseDefaultRadiusAndThickness = true;
            this.btnEdit.Click += new System.EventHandler(this.btnEdit_Click_1);
            // 
            // btnAdd
            // 
            this.btnAdd.AllowAnimations = true;
            this.btnAdd.AllowMouseEffects = true;
            this.btnAdd.AllowToggling = false;
            this.btnAdd.AnimationSpeed = 200;
            this.btnAdd.AutoGenerateColors = false;
            this.btnAdd.AutoRoundBorders = false;
            this.btnAdd.AutoSizeLeftIcon = true;
            this.btnAdd.AutoSizeRightIcon = true;
            this.btnAdd.BackColor = System.Drawing.Color.Transparent;
            this.btnAdd.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnAdd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAdd.BackgroundImage")));
            this.btnAdd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.ButtonText = "Add";
            this.btnAdd.ButtonTextMarginLeft = 0;
            this.btnAdd.ColorContrastOnClick = 45;
            this.btnAdd.ColorContrastOnHover = 45;
            this.btnAdd.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnAdd.CustomizableEdges = borderEdges3;
            this.btnAdd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAdd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAdd.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnAdd.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnAdd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAdd.Font = new System.Drawing.Font("Segoe UI", 14F, System.Drawing.FontStyle.Bold);
            this.btnAdd.ForeColor = System.Drawing.Color.Green;
            this.btnAdd.IconLeft = ((System.Drawing.Image)(resources.GetObject("btnAdd.IconLeft")));
            this.btnAdd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAdd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAdd.IconLeftPadding = new System.Windows.Forms.Padding(20, 3, 3, 3);
            this.btnAdd.IconMarginLeft = 11;
            this.btnAdd.IconPadding = 16;
            this.btnAdd.IconRight = null;
            this.btnAdd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAdd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAdd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAdd.IconSize = 25;
            this.btnAdd.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnAdd.IdleBorderRadius = 0;
            this.btnAdd.IdleBorderThickness = 0;
            this.btnAdd.IdleFillColor = System.Drawing.Color.Empty;
            this.btnAdd.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnAdd.IdleIconLeftImage")));
            this.btnAdd.IdleIconRightImage = null;
            this.btnAdd.IndicateFocus = false;
            this.btnAdd.Location = new System.Drawing.Point(52, 27);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAdd.OnDisabledState.BorderRadius = 15;
            this.btnAdd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.OnDisabledState.BorderThickness = 1;
            this.btnAdd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAdd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAdd.OnDisabledState.IconLeftImage = null;
            this.btnAdd.OnDisabledState.IconRightImage = null;
            this.btnAdd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(80)))), ((int)(((byte)(168)))), ((int)(((byte)(80)))));
            this.btnAdd.onHoverState.BorderRadius = 15;
            this.btnAdd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.onHoverState.BorderThickness = 1;
            this.btnAdd.onHoverState.FillColor = System.Drawing.SystemColors.Control;
            this.btnAdd.onHoverState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(80)))), ((int)(((byte)(168)))), ((int)(((byte)(80)))));
            this.btnAdd.onHoverState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnAdd.onHoverState.IconLeftImage")));
            this.btnAdd.onHoverState.IconRightImage = null;
            this.btnAdd.OnIdleState.BorderColor = System.Drawing.SystemColors.ControlDarkDark;
            this.btnAdd.OnIdleState.BorderRadius = 15;
            this.btnAdd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.OnIdleState.BorderThickness = 1;
            this.btnAdd.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.btnAdd.OnIdleState.ForeColor = System.Drawing.Color.Green;
            this.btnAdd.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnAdd.OnIdleState.IconLeftImage")));
            this.btnAdd.OnIdleState.IconRightImage = null;
            this.btnAdd.OnPressedState.BorderColor = System.Drawing.SystemColors.ControlDark;
            this.btnAdd.OnPressedState.BorderRadius = 15;
            this.btnAdd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.OnPressedState.BorderThickness = 1;
            this.btnAdd.OnPressedState.FillColor = System.Drawing.SystemColors.Control;
            this.btnAdd.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.btnAdd.OnPressedState.IconLeftImage = null;
            this.btnAdd.OnPressedState.IconRightImage = null;
            this.btnAdd.Size = new System.Drawing.Size(125, 65);
            this.btnAdd.TabIndex = 52;
            this.btnAdd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAdd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAdd.TextMarginLeft = 0;
            this.btnAdd.TextPadding = new System.Windows.Forms.Padding(20, 0, 0, 0);
            this.btnAdd.UseDefaultRadiusAndThickness = true;
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click_1);
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.Black;
            this.bunifuGroupBox1.BorderRadius = 4;
            this.bunifuGroupBox1.BorderThickness = 2;
            this.bunifuGroupBox1.Controls.Add(this.label5);
            this.bunifuGroupBox1.Controls.Add(this.label4);
            this.bunifuGroupBox1.Controls.Add(this.label3);
            this.bunifuGroupBox1.Controls.Add(this.label2);
            this.bunifuGroupBox1.Controls.Add(this.label1);
            this.bunifuGroupBox1.Controls.Add(this.tbxSuplierId);
            this.bunifuGroupBox1.Controls.Add(this.tbxEmail);
            this.bunifuGroupBox1.Controls.Add(this.tbxAddress);
            this.bunifuGroupBox1.Controls.Add(this.tbxSupplierName);
            this.bunifuGroupBox1.Controls.Add(this.tbxPhoneNumber);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI", 10.8F);
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(61, 12);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(978, 270);
            this.bunifuGroupBox1.TabIndex = 62;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Information Suplier";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Segoe UI Semibold", 12.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label5.Location = new System.Drawing.Point(532, 174);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(59, 23);
            this.label5.TabIndex = 56;
            this.label5.Text = "Phone";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Segoe UI Semibold", 12.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(532, 19);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(70, 23);
            this.label4.TabIndex = 55;
            this.label4.Text = "Address";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Segoe UI Semibold", 12.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(38, 174);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(51, 23);
            this.label3.TabIndex = 54;
            this.label3.Text = "Email";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Segoe UI Semibold", 12.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(38, 95);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(123, 23);
            this.label2.TabIndex = 53;
            this.label2.Text = "Supplier Name";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Segoe UI Semibold", 12.75F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(38, 23);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(27, 23);
            this.label1.TabIndex = 52;
            this.label1.Text = "ID";
            // 
            // bunifuGroupBox2
            // 
            this.bunifuGroupBox2.BorderColor = System.Drawing.Color.Black;
            this.bunifuGroupBox2.BorderRadius = 4;
            this.bunifuGroupBox2.BorderThickness = 2;
            this.bunifuGroupBox2.Controls.Add(this.btnDelete);
            this.bunifuGroupBox2.Controls.Add(this.btnEdit);
            this.bunifuGroupBox2.Controls.Add(this.btnAdd);
            this.bunifuGroupBox2.Font = new System.Drawing.Font("Segoe UI", 10.8F);
            this.bunifuGroupBox2.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox2.LabelIndent = 10;
            this.bunifuGroupBox2.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox2.Location = new System.Drawing.Point(1189, 12);
            this.bunifuGroupBox2.Name = "bunifuGroupBox2";
            this.bunifuGroupBox2.Size = new System.Drawing.Size(223, 270);
            this.bunifuGroupBox2.TabIndex = 63;
            this.bunifuGroupBox2.TabStop = false;
            this.bunifuGroupBox2.Text = "Tools";
            // 
            // SupplierView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1495, 909);
            this.Controls.Add(this.gbSupplier);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Controls.Add(this.bunifuGroupBox2);
            this.Name = "SupplierView";
            this.Text = "SupplierView";
            this.Load += new System.EventHandler(this.SuplierForm_Load);
            this.gbSupplier.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dtgvSupplier)).EndInit();
            this.bunifuGroupBox1.ResumeLayout(false);
            this.bunifuGroupBox1.PerformLayout();
            this.bunifuGroupBox2.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox tbxSuplierId;
        private Bunifu.UI.WinForms.BunifuGroupBox gbSupplier;
        private Bunifu.UI.WinForms.BunifuDataGridView dtgvSupplier;
        private Bunifu.UI.WinForms.BunifuTextBox tbxSupplierName;
        private Bunifu.UI.WinForms.BunifuTextBox tbxEmail;
        private Bunifu.UI.WinForms.BunifuTextBox tbxAddress;
        private Bunifu.UI.WinForms.BunifuTextBox tbxPhoneNumber;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDelete;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEdit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAdd;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox2;
    }
}