namespace _DoAn.Views.Suplier
{
    partial class SupplierView
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SupplierView));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.tbxID = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbxSuplierName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbxEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbxAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.tbxPhoneNumber = new Bunifu.UI.WinForms.BunifuTextBox();
            this.btnAdd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnEdit = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnDelete = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuGroupBox1 = new Bunifu.UI.WinForms.BunifuGroupBox();
            this.dtgvSupplier = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bunifuGroupBox1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dtgvSupplier)).BeginInit();
            this.SuspendLayout();
            // 
            // tbxID
            // 
            this.tbxID.AcceptsReturn = false;
            this.tbxID.AcceptsTab = false;
            this.tbxID.AnimationSpeed = 200;
            this.tbxID.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxID.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxID.AutoSizeHeight = true;
            this.tbxID.BackColor = System.Drawing.Color.Transparent;
            this.tbxID.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxID.BackgroundImage")));
            this.tbxID.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbxID.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbxID.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbxID.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbxID.BorderRadius = 1;
            this.tbxID.BorderThickness = 1;
            this.tbxID.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbxID.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxID.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxID.DefaultFont = new System.Drawing.Font("Segoe UI", 11F);
            this.tbxID.DefaultText = "";
            this.tbxID.Enabled = false;
            this.tbxID.FillColor = System.Drawing.Color.White;
            this.tbxID.HideSelection = true;
            this.tbxID.IconLeft = null;
            this.tbxID.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxID.IconPadding = 10;
            this.tbxID.IconRight = null;
            this.tbxID.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxID.Lines = new string[0];
            this.tbxID.Location = new System.Drawing.Point(40, 33);
            this.tbxID.MaxLength = 32767;
            this.tbxID.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbxID.Modified = false;
            this.tbxID.Multiline = false;
            this.tbxID.Name = "tbxID";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxID.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxID.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxID.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxID.OnIdleState = stateProperties4;
            this.tbxID.Padding = new System.Windows.Forms.Padding(3);
            this.tbxID.PasswordChar = '\0';
            this.tbxID.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxID.PlaceholderText = "ID";
            this.tbxID.ReadOnly = false;
            this.tbxID.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxID.SelectedText = "";
            this.tbxID.SelectionLength = 0;
            this.tbxID.SelectionStart = 0;
            this.tbxID.ShortcutsEnabled = true;
            this.tbxID.Size = new System.Drawing.Size(344, 42);
            this.tbxID.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxID.TabIndex = 0;
            this.tbxID.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxID.TextMarginBottom = 0;
            this.tbxID.TextMarginLeft = 3;
            this.tbxID.TextMarginTop = 1;
            this.tbxID.TextPlaceholder = "ID";
            this.tbxID.UseSystemPasswordChar = false;
            this.tbxID.WordWrap = true;
            // 
            // tbxSuplierName
            // 
            this.tbxSuplierName.AcceptsReturn = false;
            this.tbxSuplierName.AcceptsTab = false;
            this.tbxSuplierName.AnimationSpeed = 200;
            this.tbxSuplierName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxSuplierName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxSuplierName.AutoSizeHeight = true;
            this.tbxSuplierName.BackColor = System.Drawing.Color.Transparent;
            this.tbxSuplierName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxSuplierName.BackgroundImage")));
            this.tbxSuplierName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbxSuplierName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbxSuplierName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbxSuplierName.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbxSuplierName.BorderRadius = 1;
            this.tbxSuplierName.BorderThickness = 1;
            this.tbxSuplierName.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbxSuplierName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxSuplierName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxSuplierName.DefaultFont = new System.Drawing.Font("Segoe UI", 11F);
            this.tbxSuplierName.DefaultText = "";
            this.tbxSuplierName.FillColor = System.Drawing.Color.White;
            this.tbxSuplierName.HideSelection = true;
            this.tbxSuplierName.IconLeft = null;
            this.tbxSuplierName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxSuplierName.IconPadding = 10;
            this.tbxSuplierName.IconRight = null;
            this.tbxSuplierName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxSuplierName.Lines = new string[0];
            this.tbxSuplierName.Location = new System.Drawing.Point(40, 92);
            this.tbxSuplierName.MaxLength = 32767;
            this.tbxSuplierName.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbxSuplierName.Modified = false;
            this.tbxSuplierName.Multiline = false;
            this.tbxSuplierName.Name = "tbxSuplierName";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxSuplierName.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxSuplierName.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxSuplierName.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxSuplierName.OnIdleState = stateProperties8;
            this.tbxSuplierName.Padding = new System.Windows.Forms.Padding(3);
            this.tbxSuplierName.PasswordChar = '\0';
            this.tbxSuplierName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxSuplierName.PlaceholderText = "Suplier Name";
            this.tbxSuplierName.ReadOnly = false;
            this.tbxSuplierName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxSuplierName.SelectedText = "";
            this.tbxSuplierName.SelectionLength = 0;
            this.tbxSuplierName.SelectionStart = 0;
            this.tbxSuplierName.ShortcutsEnabled = true;
            this.tbxSuplierName.Size = new System.Drawing.Size(344, 42);
            this.tbxSuplierName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxSuplierName.TabIndex = 1;
            this.tbxSuplierName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxSuplierName.TextMarginBottom = 0;
            this.tbxSuplierName.TextMarginLeft = 3;
            this.tbxSuplierName.TextMarginTop = 1;
            this.tbxSuplierName.TextPlaceholder = "Suplier Name";
            this.tbxSuplierName.UseSystemPasswordChar = false;
            this.tbxSuplierName.WordWrap = true;
            this.tbxSuplierName.TextChanged += new System.EventHandler(this.tbxSuplierName_TextChanged);
            // 
            // tbxEmail
            // 
            this.tbxEmail.AcceptsReturn = false;
            this.tbxEmail.AcceptsTab = false;
            this.tbxEmail.AnimationSpeed = 200;
            this.tbxEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxEmail.AutoSizeHeight = true;
            this.tbxEmail.BackColor = System.Drawing.Color.Transparent;
            this.tbxEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxEmail.BackgroundImage")));
            this.tbxEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbxEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbxEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbxEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbxEmail.BorderRadius = 1;
            this.tbxEmail.BorderThickness = 1;
            this.tbxEmail.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbxEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 11F);
            this.tbxEmail.DefaultText = "";
            this.tbxEmail.FillColor = System.Drawing.Color.White;
            this.tbxEmail.HideSelection = true;
            this.tbxEmail.IconLeft = null;
            this.tbxEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxEmail.IconPadding = 10;
            this.tbxEmail.IconRight = null;
            this.tbxEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxEmail.Lines = new string[0];
            this.tbxEmail.Location = new System.Drawing.Point(40, 155);
            this.tbxEmail.MaxLength = 32767;
            this.tbxEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbxEmail.Modified = false;
            this.tbxEmail.Multiline = false;
            this.tbxEmail.Name = "tbxEmail";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxEmail.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxEmail.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxEmail.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxEmail.OnIdleState = stateProperties12;
            this.tbxEmail.Padding = new System.Windows.Forms.Padding(3);
            this.tbxEmail.PasswordChar = '\0';
            this.tbxEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxEmail.PlaceholderText = "Email";
            this.tbxEmail.ReadOnly = false;
            this.tbxEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxEmail.SelectedText = "";
            this.tbxEmail.SelectionLength = 0;
            this.tbxEmail.SelectionStart = 0;
            this.tbxEmail.ShortcutsEnabled = true;
            this.tbxEmail.Size = new System.Drawing.Size(344, 42);
            this.tbxEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxEmail.TabIndex = 2;
            this.tbxEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxEmail.TextMarginBottom = 0;
            this.tbxEmail.TextMarginLeft = 3;
            this.tbxEmail.TextMarginTop = 1;
            this.tbxEmail.TextPlaceholder = "Email";
            this.tbxEmail.UseSystemPasswordChar = false;
            this.tbxEmail.WordWrap = true;
            this.tbxEmail.TextChanged += new System.EventHandler(this.tbxSuplierName_TextChanged);
            // 
            // tbxAddress
            // 
            this.tbxAddress.AcceptsReturn = false;
            this.tbxAddress.AcceptsTab = false;
            this.tbxAddress.AnimationSpeed = 200;
            this.tbxAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxAddress.AutoSizeHeight = true;
            this.tbxAddress.BackColor = System.Drawing.Color.Transparent;
            this.tbxAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxAddress.BackgroundImage")));
            this.tbxAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbxAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbxAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbxAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbxAddress.BorderRadius = 1;
            this.tbxAddress.BorderThickness = 1;
            this.tbxAddress.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbxAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 11F);
            this.tbxAddress.DefaultText = "";
            this.tbxAddress.FillColor = System.Drawing.Color.White;
            this.tbxAddress.HideSelection = true;
            this.tbxAddress.IconLeft = null;
            this.tbxAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxAddress.IconPadding = 10;
            this.tbxAddress.IconRight = null;
            this.tbxAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxAddress.Lines = new string[0];
            this.tbxAddress.Location = new System.Drawing.Point(408, 33);
            this.tbxAddress.MaxLength = 32767;
            this.tbxAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbxAddress.Modified = false;
            this.tbxAddress.Multiline = false;
            this.tbxAddress.Name = "tbxAddress";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxAddress.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxAddress.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxAddress.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxAddress.OnIdleState = stateProperties16;
            this.tbxAddress.Padding = new System.Windows.Forms.Padding(3);
            this.tbxAddress.PasswordChar = '\0';
            this.tbxAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxAddress.PlaceholderText = "Address";
            this.tbxAddress.ReadOnly = false;
            this.tbxAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxAddress.SelectedText = "";
            this.tbxAddress.SelectionLength = 0;
            this.tbxAddress.SelectionStart = 0;
            this.tbxAddress.ShortcutsEnabled = true;
            this.tbxAddress.Size = new System.Drawing.Size(344, 101);
            this.tbxAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxAddress.TabIndex = 3;
            this.tbxAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxAddress.TextMarginBottom = 0;
            this.tbxAddress.TextMarginLeft = 3;
            this.tbxAddress.TextMarginTop = 1;
            this.tbxAddress.TextPlaceholder = "Address";
            this.tbxAddress.UseSystemPasswordChar = false;
            this.tbxAddress.WordWrap = true;
            this.tbxAddress.TextChanged += new System.EventHandler(this.tbxSuplierName_TextChanged);
            // 
            // tbxPhoneNumber
            // 
            this.tbxPhoneNumber.AcceptsReturn = false;
            this.tbxPhoneNumber.AcceptsTab = false;
            this.tbxPhoneNumber.AnimationSpeed = 200;
            this.tbxPhoneNumber.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.tbxPhoneNumber.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.tbxPhoneNumber.AutoSizeHeight = true;
            this.tbxPhoneNumber.BackColor = System.Drawing.Color.Transparent;
            this.tbxPhoneNumber.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("tbxPhoneNumber.BackgroundImage")));
            this.tbxPhoneNumber.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.tbxPhoneNumber.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.tbxPhoneNumber.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.tbxPhoneNumber.BorderColorIdle = System.Drawing.Color.Silver;
            this.tbxPhoneNumber.BorderRadius = 1;
            this.tbxPhoneNumber.BorderThickness = 1;
            this.tbxPhoneNumber.CharacterCase = Bunifu.UI.WinForms.BunifuTextBox.CharacterCases.Normal;
            this.tbxPhoneNumber.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.tbxPhoneNumber.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxPhoneNumber.DefaultFont = new System.Drawing.Font("Segoe UI", 11F);
            this.tbxPhoneNumber.DefaultText = "";
            this.tbxPhoneNumber.FillColor = System.Drawing.Color.White;
            this.tbxPhoneNumber.HideSelection = true;
            this.tbxPhoneNumber.IconLeft = null;
            this.tbxPhoneNumber.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxPhoneNumber.IconPadding = 10;
            this.tbxPhoneNumber.IconRight = null;
            this.tbxPhoneNumber.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.tbxPhoneNumber.Lines = new string[0];
            this.tbxPhoneNumber.Location = new System.Drawing.Point(408, 155);
            this.tbxPhoneNumber.MaxLength = 32767;
            this.tbxPhoneNumber.MinimumSize = new System.Drawing.Size(1, 1);
            this.tbxPhoneNumber.Modified = false;
            this.tbxPhoneNumber.Multiline = false;
            this.tbxPhoneNumber.Name = "tbxPhoneNumber";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxPhoneNumber.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.tbxPhoneNumber.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxPhoneNumber.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.tbxPhoneNumber.OnIdleState = stateProperties20;
            this.tbxPhoneNumber.Padding = new System.Windows.Forms.Padding(3);
            this.tbxPhoneNumber.PasswordChar = '\0';
            this.tbxPhoneNumber.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.tbxPhoneNumber.PlaceholderText = "Phone Number";
            this.tbxPhoneNumber.ReadOnly = false;
            this.tbxPhoneNumber.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.tbxPhoneNumber.SelectedText = "";
            this.tbxPhoneNumber.SelectionLength = 0;
            this.tbxPhoneNumber.SelectionStart = 0;
            this.tbxPhoneNumber.ShortcutsEnabled = true;
            this.tbxPhoneNumber.Size = new System.Drawing.Size(344, 42);
            this.tbxPhoneNumber.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.tbxPhoneNumber.TabIndex = 4;
            this.tbxPhoneNumber.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.tbxPhoneNumber.TextMarginBottom = 0;
            this.tbxPhoneNumber.TextMarginLeft = 3;
            this.tbxPhoneNumber.TextMarginTop = 1;
            this.tbxPhoneNumber.TextPlaceholder = "Phone Number";
            this.tbxPhoneNumber.UseSystemPasswordChar = false;
            this.tbxPhoneNumber.WordWrap = true;
            this.tbxPhoneNumber.TextChanged += new System.EventHandler(this.tbxSuplierName_TextChanged);
            // 
            // btnAdd
            // 
            this.btnAdd.AllowAnimations = true;
            this.btnAdd.AllowMouseEffects = true;
            this.btnAdd.AllowToggling = false;
            this.btnAdd.AnimationSpeed = 200;
            this.btnAdd.AutoGenerateColors = false;
            this.btnAdd.AutoRoundBorders = false;
            this.btnAdd.AutoSizeLeftIcon = true;
            this.btnAdd.AutoSizeRightIcon = true;
            this.btnAdd.BackColor = System.Drawing.Color.Transparent;
            this.btnAdd.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnAdd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAdd.BackgroundImage")));
            this.btnAdd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.ButtonText = "Add";
            this.btnAdd.ButtonTextMarginLeft = 0;
            this.btnAdd.ColorContrastOnClick = 45;
            this.btnAdd.ColorContrastOnHover = 45;
            this.btnAdd.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnAdd.CustomizableEdges = borderEdges1;
            this.btnAdd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAdd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAdd.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnAdd.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnAdd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAdd.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnAdd.ForeColor = System.Drawing.Color.ForestGreen;
            this.btnAdd.IconLeft = null;
            this.btnAdd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAdd.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAdd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAdd.IconMarginLeft = 11;
            this.btnAdd.IconPadding = 10;
            this.btnAdd.IconRight = null;
            this.btnAdd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAdd.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAdd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAdd.IconSize = 25;
            this.btnAdd.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnAdd.IdleBorderRadius = 0;
            this.btnAdd.IdleBorderThickness = 0;
            this.btnAdd.IdleFillColor = System.Drawing.Color.Empty;
            this.btnAdd.IdleIconLeftImage = null;
            this.btnAdd.IdleIconRightImage = null;
            this.btnAdd.IndicateFocus = false;
            this.btnAdd.Location = new System.Drawing.Point(796, 33);
            this.btnAdd.Name = "btnAdd";
            this.btnAdd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAdd.OnDisabledState.BorderRadius = 4;
            this.btnAdd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.OnDisabledState.BorderThickness = 1;
            this.btnAdd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAdd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAdd.OnDisabledState.IconLeftImage = null;
            this.btnAdd.OnDisabledState.IconRightImage = null;
            this.btnAdd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnAdd.onHoverState.BorderRadius = 4;
            this.btnAdd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.onHoverState.BorderThickness = 1;
            this.btnAdd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnAdd.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAdd.onHoverState.IconLeftImage = null;
            this.btnAdd.onHoverState.IconRightImage = null;
            this.btnAdd.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnAdd.OnIdleState.BorderRadius = 4;
            this.btnAdd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.OnIdleState.BorderThickness = 1;
            this.btnAdd.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.btnAdd.OnIdleState.ForeColor = System.Drawing.Color.ForestGreen;
            this.btnAdd.OnIdleState.IconLeftImage = null;
            this.btnAdd.OnIdleState.IconRightImage = null;
            this.btnAdd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAdd.OnPressedState.BorderRadius = 4;
            this.btnAdd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAdd.OnPressedState.BorderThickness = 1;
            this.btnAdd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAdd.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAdd.OnPressedState.IconLeftImage = null;
            this.btnAdd.OnPressedState.IconRightImage = null;
            this.btnAdd.Size = new System.Drawing.Size(150, 39);
            this.btnAdd.TabIndex = 5;
            this.btnAdd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAdd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAdd.TextMarginLeft = 0;
            this.btnAdd.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAdd.UseDefaultRadiusAndThickness = true;
            this.btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
            // 
            // btnEdit
            // 
            this.btnEdit.AllowAnimations = true;
            this.btnEdit.AllowMouseEffects = true;
            this.btnEdit.AllowToggling = false;
            this.btnEdit.AnimationSpeed = 200;
            this.btnEdit.AutoGenerateColors = false;
            this.btnEdit.AutoRoundBorders = false;
            this.btnEdit.AutoSizeLeftIcon = true;
            this.btnEdit.AutoSizeRightIcon = true;
            this.btnEdit.BackColor = System.Drawing.Color.Transparent;
            this.btnEdit.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnEdit.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnEdit.BackgroundImage")));
            this.btnEdit.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEdit.ButtonText = "Edit";
            this.btnEdit.ButtonTextMarginLeft = 0;
            this.btnEdit.ColorContrastOnClick = 45;
            this.btnEdit.ColorContrastOnHover = 45;
            this.btnEdit.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnEdit.CustomizableEdges = borderEdges2;
            this.btnEdit.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnEdit.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEdit.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnEdit.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnEdit.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnEdit.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnEdit.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(102)))));
            this.btnEdit.IconLeft = null;
            this.btnEdit.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnEdit.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnEdit.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnEdit.IconMarginLeft = 11;
            this.btnEdit.IconPadding = 10;
            this.btnEdit.IconRight = null;
            this.btnEdit.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnEdit.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnEdit.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnEdit.IconSize = 25;
            this.btnEdit.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnEdit.IdleBorderRadius = 0;
            this.btnEdit.IdleBorderThickness = 0;
            this.btnEdit.IdleFillColor = System.Drawing.Color.Empty;
            this.btnEdit.IdleIconLeftImage = null;
            this.btnEdit.IdleIconRightImage = null;
            this.btnEdit.IndicateFocus = false;
            this.btnEdit.Location = new System.Drawing.Point(796, 92);
            this.btnEdit.Name = "btnEdit";
            this.btnEdit.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnEdit.OnDisabledState.BorderRadius = 4;
            this.btnEdit.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEdit.OnDisabledState.BorderThickness = 1;
            this.btnEdit.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnEdit.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnEdit.OnDisabledState.IconLeftImage = null;
            this.btnEdit.OnDisabledState.IconRightImage = null;
            this.btnEdit.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnEdit.onHoverState.BorderRadius = 4;
            this.btnEdit.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEdit.onHoverState.BorderThickness = 1;
            this.btnEdit.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnEdit.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnEdit.onHoverState.IconLeftImage = null;
            this.btnEdit.onHoverState.IconRightImage = null;
            this.btnEdit.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnEdit.OnIdleState.BorderRadius = 4;
            this.btnEdit.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEdit.OnIdleState.BorderThickness = 1;
            this.btnEdit.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.btnEdit.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(128)))), ((int)(((byte)(102)))));
            this.btnEdit.OnIdleState.IconLeftImage = null;
            this.btnEdit.OnIdleState.IconRightImage = null;
            this.btnEdit.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEdit.OnPressedState.BorderRadius = 4;
            this.btnEdit.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnEdit.OnPressedState.BorderThickness = 1;
            this.btnEdit.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnEdit.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnEdit.OnPressedState.IconLeftImage = null;
            this.btnEdit.OnPressedState.IconRightImage = null;
            this.btnEdit.Size = new System.Drawing.Size(150, 39);
            this.btnEdit.TabIndex = 6;
            this.btnEdit.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnEdit.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnEdit.TextMarginLeft = 0;
            this.btnEdit.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnEdit.UseDefaultRadiusAndThickness = true;
            this.btnEdit.Click += new System.EventHandler(this.btnEdit_Click);
            // 
            // btnDelete
            // 
            this.btnDelete.AllowAnimations = true;
            this.btnDelete.AllowMouseEffects = true;
            this.btnDelete.AllowToggling = false;
            this.btnDelete.AnimationSpeed = 200;
            this.btnDelete.AutoGenerateColors = false;
            this.btnDelete.AutoRoundBorders = false;
            this.btnDelete.AutoSizeLeftIcon = true;
            this.btnDelete.AutoSizeRightIcon = true;
            this.btnDelete.BackColor = System.Drawing.Color.Transparent;
            this.btnDelete.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(51)))), ((int)(((byte)(122)))), ((int)(((byte)(183)))));
            this.btnDelete.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnDelete.BackgroundImage")));
            this.btnDelete.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.ButtonText = "Delete";
            this.btnDelete.ButtonTextMarginLeft = 0;
            this.btnDelete.ColorContrastOnClick = 45;
            this.btnDelete.ColorContrastOnHover = 45;
            this.btnDelete.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnDelete.CustomizableEdges = borderEdges3;
            this.btnDelete.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnDelete.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelete.DisabledFillColor = System.Drawing.Color.Empty;
            this.btnDelete.DisabledForecolor = System.Drawing.Color.Empty;
            this.btnDelete.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnDelete.Font = new System.Drawing.Font("Segoe UI", 11.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnDelete.ForeColor = System.Drawing.Color.Red;
            this.btnDelete.IconLeft = null;
            this.btnDelete.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnDelete.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelete.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnDelete.IconMarginLeft = 11;
            this.btnDelete.IconPadding = 10;
            this.btnDelete.IconRight = null;
            this.btnDelete.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnDelete.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnDelete.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnDelete.IconSize = 25;
            this.btnDelete.IdleBorderColor = System.Drawing.Color.Empty;
            this.btnDelete.IdleBorderRadius = 0;
            this.btnDelete.IdleBorderThickness = 0;
            this.btnDelete.IdleFillColor = System.Drawing.Color.Empty;
            this.btnDelete.IdleIconLeftImage = null;
            this.btnDelete.IdleIconRightImage = null;
            this.btnDelete.IndicateFocus = false;
            this.btnDelete.Location = new System.Drawing.Point(796, 155);
            this.btnDelete.Name = "btnDelete";
            this.btnDelete.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnDelete.OnDisabledState.BorderRadius = 4;
            this.btnDelete.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnDisabledState.BorderThickness = 1;
            this.btnDelete.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnDelete.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnDelete.OnDisabledState.IconLeftImage = null;
            this.btnDelete.OnDisabledState.IconRightImage = null;
            this.btnDelete.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnDelete.onHoverState.BorderRadius = 4;
            this.btnDelete.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.onHoverState.BorderThickness = 1;
            this.btnDelete.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(30)))), ((int)(((byte)(150)))), ((int)(((byte)(255)))));
            this.btnDelete.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnDelete.onHoverState.IconLeftImage = null;
            this.btnDelete.onHoverState.IconRightImage = null;
            this.btnDelete.OnIdleState.BorderColor = System.Drawing.Color.Black;
            this.btnDelete.OnIdleState.BorderRadius = 4;
            this.btnDelete.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnIdleState.BorderThickness = 1;
            this.btnDelete.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.btnDelete.OnIdleState.ForeColor = System.Drawing.Color.Red;
            this.btnDelete.OnIdleState.IconLeftImage = null;
            this.btnDelete.OnIdleState.IconRightImage = null;
            this.btnDelete.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDelete.OnPressedState.BorderRadius = 4;
            this.btnDelete.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnDelete.OnPressedState.BorderThickness = 1;
            this.btnDelete.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnDelete.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnDelete.OnPressedState.IconLeftImage = null;
            this.btnDelete.OnPressedState.IconRightImage = null;
            this.btnDelete.Size = new System.Drawing.Size(150, 39);
            this.btnDelete.TabIndex = 7;
            this.btnDelete.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnDelete.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnDelete.TextMarginLeft = 0;
            this.btnDelete.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnDelete.UseDefaultRadiusAndThickness = true;
            this.btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
            // 
            // bunifuGroupBox1
            // 
            this.bunifuGroupBox1.BorderColor = System.Drawing.Color.Black;
            this.bunifuGroupBox1.BorderRadius = 4;
            this.bunifuGroupBox1.BorderThickness = 2;
            this.bunifuGroupBox1.Controls.Add(this.dtgvSupplier);
            this.bunifuGroupBox1.Font = new System.Drawing.Font("Segoe UI", 10.8F);
            this.bunifuGroupBox1.LabelAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bunifuGroupBox1.LabelIndent = 10;
            this.bunifuGroupBox1.LineStyle = Bunifu.UI.WinForms.BunifuGroupBox.LineStyles.Solid;
            this.bunifuGroupBox1.Location = new System.Drawing.Point(40, 223);
            this.bunifuGroupBox1.Name = "bunifuGroupBox1";
            this.bunifuGroupBox1.Size = new System.Drawing.Size(906, 387);
            this.bunifuGroupBox1.TabIndex = 8;
            this.bunifuGroupBox1.TabStop = false;
            this.bunifuGroupBox1.Text = "Suppliers Table";
            // 
            // dtgvSupplier
            // 
            this.dtgvSupplier.AllowCustomTheming = true;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dtgvSupplier.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dtgvSupplier.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dtgvSupplier.BackgroundColor = System.Drawing.SystemColors.ButtonFace;
            this.dtgvSupplier.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dtgvSupplier.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dtgvSupplier.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.ForestGreen;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dtgvSupplier.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dtgvSupplier.ColumnHeadersHeight = 40;
            this.dtgvSupplier.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dtgvSupplier.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtgvSupplier.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtgvSupplier.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtgvSupplier.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dtgvSupplier.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dtgvSupplier.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtgvSupplier.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.ForestGreen;
            this.dtgvSupplier.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dtgvSupplier.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dtgvSupplier.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dtgvSupplier.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dtgvSupplier.CurrentTheme.Name = null;
            this.dtgvSupplier.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dtgvSupplier.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dtgvSupplier.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dtgvSupplier.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dtgvSupplier.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dtgvSupplier.DefaultCellStyle = dataGridViewCellStyle3;
            this.dtgvSupplier.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dtgvSupplier.EnableHeadersVisualStyles = false;
            this.dtgvSupplier.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dtgvSupplier.HeaderBackColor = System.Drawing.Color.ForestGreen;
            this.dtgvSupplier.HeaderBgColor = System.Drawing.Color.Empty;
            this.dtgvSupplier.HeaderForeColor = System.Drawing.Color.White;
            this.dtgvSupplier.Location = new System.Drawing.Point(3, 23);
            this.dtgvSupplier.Name = "dtgvSupplier";
            this.dtgvSupplier.ReadOnly = true;
            this.dtgvSupplier.RowHeadersVisible = false;
            this.dtgvSupplier.RowTemplate.Height = 40;
            this.dtgvSupplier.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dtgvSupplier.Size = new System.Drawing.Size(900, 361);
            this.dtgvSupplier.TabIndex = 61;
            this.dtgvSupplier.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dtgvSupplier.DoubleClick += new System.EventHandler(this.dtgvSupplier_DoubleClick);
            // 
            // SupplierView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(974, 622);
            this.Controls.Add(this.bunifuGroupBox1);
            this.Controls.Add(this.btnDelete);
            this.Controls.Add(this.btnEdit);
            this.Controls.Add(this.btnAdd);
            this.Controls.Add(this.tbxPhoneNumber);
            this.Controls.Add(this.tbxAddress);
            this.Controls.Add(this.tbxEmail);
            this.Controls.Add(this.tbxSuplierName);
            this.Controls.Add(this.tbxID);
            this.Name = "SupplierView";
            this.Text = "SuplierView";
            this.Load += new System.EventHandler(this.SupplierView_Load);
            this.bunifuGroupBox1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.dtgvSupplier)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox tbxID;
        private Bunifu.UI.WinForms.BunifuTextBox tbxSuplierName;
        private Bunifu.UI.WinForms.BunifuTextBox tbxEmail;
        private Bunifu.UI.WinForms.BunifuTextBox tbxAddress;
        private Bunifu.UI.WinForms.BunifuTextBox tbxPhoneNumber;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAdd;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnEdit;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnDelete;
        private Bunifu.UI.WinForms.BunifuGroupBox bunifuGroupBox1;
        private Bunifu.UI.WinForms.BunifuDataGridView dtgvSupplier;
    }
}